# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <emil@emil-pc>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-11 18:49+0300\n"
"PO-Revision-Date: 2020-07-30 11:25+0300\n"
"Last-Translator: Emil <emil@emil-pc>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../common/log/journal.py:189
msgid "INFO message from VeiL Broker."
msgstr "Информационное сообщение с VeiL VDI брокера."

#: ../common/log/journal.py:206
msgid "Warning message from VeiL Broker."
msgstr "Сообщение о предупреждении на VeiL VDI брокера."

#: ../common/log/journal.py:223
msgid "Error message from VeiL Broker."
msgstr "Сообщение об ошибке на VeiL VDI брокера."

#: ../common/log/journal.py:256
msgid "SMTP server is not configured."
msgstr "SMTP сервер не настроен."

#: ../common/log/journal.py:299
msgid "Error in smtp server: {}."
msgstr "Ошибка связанная с SMTP сервером: {}."

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:84
msgid "Add new journal archive."
msgstr "Добавлен новый архив журнала."

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:85
msgid "Archive name:"
msgstr "Имя архива:"

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:86
msgid "path:"
msgstr "путь:"

#: ../common/models/active_tk_connection.py:158
msgid "User {} connected to VM {}."
msgstr "Пользователь {} подключился к ВМ {}."

#: ../common/models/active_tk_connection.py:167
msgid "User {} disconnected from VM {}."
msgstr "Пользователь {} отключился от ВМ {}."

#: ../common/models/active_tk_connection.py:190
msgid "User {} failed to connect to VM {}."
msgstr "Пользователю {} не удалось подключиться к ВМ {}."

#: ../common/models/active_tk_connection.py:192
msgid "Error code: {}. Error message: {}."
msgstr "Код ошибки: {}. Сообщение об ошибке: {}."

#: ../common/models/auth.py:237 ../common/models/auth.py:640
#: ../web_app/auth/user_schema.py:35
msgid "username can`t be empty."
msgstr "имя пользователя не может быть пустым."

#: ../common/models/auth.py:242 ../web_app/auth/user_schema.py:40
msgid "username must be <= 128 characters."
msgstr "имя пользователя должно быть <= 128 символов."

#: ../common/models/auth.py:249
msgid "username {} must contain letters, digits, _, +, begin from letter and can't contain any spaces."
msgstr "имя пользователя {} должно состоять из букв, цифр, _, +, начинаться с буквы и не содержать пробелов."

#: ../common/models/auth.py:280
msgid "Role {} is added to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:288 ../common/models/auth.py:316
msgid "User {} roles: {}."
msgstr "Роли пользователя {}: {}."

#: ../common/models/auth.py:293
msgid "Role {} is assigned to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:305
msgid "Roles: {} was deleted to user {}."
msgstr "Роли: {} удалены у пользователя {}."

#: ../common/models/auth.py:364
msgid "User {} already has permission {}."
msgstr "Пользователь {} уже имеет разрешение."

#: ../common/models/auth.py:372
msgid "Permission(s) {} added to user {}."
msgstr "Разрешения {} назначены пользователю {}."

#: ../common/models/auth.py:395
msgid "Permission(s) {} removed from user {}."
msgstr "Разрешения {} удалены у пользователя {}."

#: ../common/models/auth.py:404
msgid "User {} permission(s): {}."
msgstr "Разрешения пользователя {}: {}."

#: ../common/models/auth.py:418
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: ../common/models/auth.py:429
#, python-brace-format
msgid "User {username} has been activated on Astra."
msgstr "Пользователь {username} был активирован в системе."

#: ../common/models/auth.py:450
msgid "There is no more active superuser."
msgstr "Больше нет активного администратора."

#: ../common/models/auth.py:459
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: ../common/models/auth.py:481
#, python-brace-format
msgid "User {username} has been deactivated on Astra."
msgstr "Пользователь {username} деактивирован в системе."

#: ../common/models/auth.py:526
msgid "Invalid credentials. Check or create password for user {}."
msgstr "Неверные учетные данные. Проверьте или создайте пароль для пользователя {}."

#: ../common/models/auth.py:536 ../common/models/auth.py:584
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: ../common/models/auth.py:542
#, python-brace-format
msgid "Password of user {username} has`t been changed."
msgstr "Пароль пользователя {username} не был изменен."

#: ../common/models/auth.py:581
msgid "Password of user {} has been changed to the local password."
msgstr "Пароль пользователя {} изменен на локальный пароль."

#: ../common/models/auth.py:663
msgid "Superuser."
msgstr "Администратор."

#: ../common/models/auth.py:663 ../common/models/auth.py:677
#: ../common/models/auth.py:689
msgid "User."
msgstr "Пользователь."

#: ../common/models/auth.py:679
msgid "You must change password for user {}. Check a reason in description."
msgstr "Необходимо изменить пароль для пользователя {}. Причина в описании."

#: ../common/models/auth.py:693
msgid "User {} was created in Astra Linux before. Please try to create him with correct password or delete in Astra Linux before trying to create in VeiL VDI again."
msgstr "Пользователь {} был ранее создан в Astra Linux. Пожалуйста, попробуйте создать его с правильным паролем или удалите его в Astra Linux, прежде чем снова пытаться создать в VeiL VDI."

#: ../common/models/auth.py:697
msgid "User {} was created in Astra Linux before. Please delete him there before trying to create in Broker again."
msgstr "Пользователь {} был ранее создан в Astra Linux. Пожалуйста удалите его оттуда, прежде чем снова пересоздать в Брокере."

#: ../common/models/auth.py:707
msgid "User {} creation error."
msgstr "Ошибка создания пользователя {}."

#: ../common/models/auth.py:717
msgid "Your password is incorrect for user {}. Check description in journal."
msgstr "Пароль неверен для пользователя {}. Проверьте описание в журнале."

#: ../common/models/auth.py:727
msgid "{} {} created."
msgstr "{} {} создан."

#: ../common/models/auth.py:786
msgid "User {} update error."
msgstr "Ошибка обновления пользователя {}."

#: ../common/models/auth.py:798
msgid "Values of user {} is changed."
msgstr "Параметры пользователя {} изменены."

#: ../common/models/auth.py:805 ../common/models/auth.py:816
msgid "Roles: {}."
msgstr "Роли: {}."

#: ../common/models/auth.py:806
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал администратором."

#: ../common/models/auth.py:817
#, python-brace-format
msgid "User {username} is no longer a superuser."
msgstr "Пользователь {username} перестал быть администратором."

#: ../common/models/auth.py:848
#, python-brace-format
msgid "User {username} has been logged in."
msgstr "Пользователь {username} вошел в систему."

#: ../common/models/auth.py:851
msgid "Auth type: {}, IP: {}, Client type: {}."
msgstr "Тип авторизации: {}, IP: {}, тип клиента: {}."

#: ../common/models/auth.py:874
#, python-brace-format
msgid "User {username} has been logged out."
msgstr "Пользователь {username} вышел из системы."

#: ../common/models/auth.py:891
msgid "QR code and secret code of 2fa were repeated for user {}."
msgstr "QR код и секретный код для двухфакторной аутентификации были повторены для пользователя {}."

#: ../common/models/auth.py:895
msgid "New QR code and secret code of 2fa were generated for user {}."
msgstr "Новый QR код и секретный код для двухфакторной аутентификации были созданы для пользователя {}."

#: ../common/models/auth.py:910
msgid "One-time password does not match or is out of date."
msgstr "Одноразовый пароль не совпадает или устарел."

#: ../common/models/auth.py:1035
msgid "Group {} is created."
msgstr "Группа {} создана."

#: ../common/models/auth.py:1062
msgid "Group {} already has permission {}."
msgstr "Группа {} уже имеет разрешение {}."

#: ../common/models/auth.py:1070
msgid "Permission(s) {} added to group {}."
msgstr "Разрешения: {} добавлены группе {}."

#: ../common/models/auth.py:1093
msgid "Permission(s) {} removed from group {}."
msgstr "Разрешения {} удалены у группы {}."

#: ../common/models/auth.py:1102
msgid "Group {} permission(s): {}."
msgstr "Разрешения группы {}: {}."

#: ../common/models/auth.py:1120
msgid "Values of group {} is updated."
msgstr "Параметры группы {} обновлены."

#: ../common/models/auth.py:1142
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: ../common/models/auth.py:1149
msgid "User {} is already in group {}."
msgstr "Пользователь {} уже находится в группе {}."

#: ../common/models/auth.py:1161
msgid "Removing user {} from group {}."
msgstr "Удаление пользователя {} из группы {}."

#: ../common/models/auth.py:1174
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: ../common/models/auth.py:1181
msgid "Group {} has already role {}."
msgstr "Группе {} уже назначена роль {}."

#: ../common/models/auth.py:1194
msgid "Roles: {} was deleted to group {}."
msgstr "Роли: {} удалены из группы {}."

#: ../common/models/authentication_directory.py:191
#: ../web_app/tests/test_auth_dir.py:177
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной службы каталогов."

#: ../common/models/authentication_directory.py:215
msgid "Authentication directory {} is created."
msgstr "Служба каталогов {} создана."

#: ../common/models/authentication_directory.py:250
msgid "Values for auth directory is updated."
msgstr "Значения службы каталогов обновлены."

#: ../common/models/authentication_directory.py:285
msgid "Arguments: {} of group: {}."
msgstr "Аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:288
msgid "Mapping for auth directory {} is created."
msgstr "Сопоставление для службы каталогов {} создано."

#: ../common/models/authentication_directory.py:324
msgid "New arguments: {} of group: {}."
msgstr "Новые аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:327
msgid "Mapping for auth directory {} is updated."
msgstr "Сопоставление для службы каталогов {} обновлено."

#: ../common/models/authentication_directory.py:356
#: ../common/models/authentication_directory.py:732
msgid "Failed to connect to authentication directory server {}."
msgstr "Не удалось подключиться к серверу службы каталогов LDAP {}."

#: ../common/models/authentication_directory.py:366
msgid "Authentication directory server {} is connected."
msgstr "Сервер службы каталогов {} подключен."

#: ../common/models/authentication_directory.py:452
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: ../common/models/authentication_directory.py:469
msgid "something other."
msgstr "что-то другое."

#: ../common/models/authentication_directory.py:470
msgid "Username {} is incorrect. Maybe you mean {}."
msgstr "Имя пользователя {} неверное. Может быть вы имели в виду {}."

#: ../common/models/authentication_directory.py:474
msgid "User {} is deactivate."
msgstr "Пользователь {} деактивирован."

#: ../common/models/authentication_directory.py:505
msgid "Mappings: {}."
msgstr "Сопоставления: {}."

#: ../common/models/authentication_directory.py:529
msgid "escaped values: {}."
msgstr "скрытые значения: {}."

#: ../common/models/authentication_directory.py:531
msgid "role mapping value type: {}."
msgstr "тип значений отображения роли: {}."

#: ../common/models/authentication_directory.py:544
msgid "User VeiL groups: {}."
msgstr "Группы пользователей VeiL: {}."

#: ../common/models/authentication_directory.py:552
msgid "Attaching user {} to group: {}."
msgstr "Прикрепление пользователя {} к группе {}."

#: ../common/models/authentication_directory.py:573
#: ../common/models/authentication_directory.py:584
msgid "No authentication directory controllers."
msgstr "Нет контроллеров служб каталогов."

#: ../common/models/authentication_directory.py:611
#: ../web_app/auth/handlers.py:63
msgid "Invalid credentials."
msgstr "Неверные учетные данные."

#: ../common/models/authentication_directory.py:629
#: ../common/models/authentication_directory.py:666
msgid "Invalid credentials (ldap): {}."
msgstr "Неверные учетные данные (ldap): {}."

#: ../common/models/authentication_directory.py:635
#: ../common/models/authentication_directory.py:672
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: ../common/models/authentication_directory.py:640
msgid "The LDAP server provides an alternate address to which an LDAP request can be processed, but the attempt was unsuccessful."
msgstr "Сервер LDAP предоставляет альтернативный адрес, по которому может быть обработан запрос LDAP, но попытка было неудачной."

#: ../common/models/authentication_directory.py:716
msgid "LDAP username and password can`t be empty."
msgstr "Имя пользователя и пароль LDAP не могут быть пустыми."

#: ../common/models/authentication_directory.py:725
msgid "Authentication directory server {} has bad auth info."
msgstr "Не удалось подключиться к серверу службы каталогов {}."

#: ../common/models/authentication_directory.py:864
#: ../common/models/authentication_directory.py:1032
msgid "Fail to connect to Authentication Directory. Check service information."
msgstr "Ошибка подключения к службе каталогов."

#: ../common/models/authentication_directory.py:1090
msgid "{} new users synced from Authentication Directory."
msgstr "{} новых пользователей синхронизировано из службы каталогов."

#: ../common/models/authentication_directory.py:1102
#: ../web_app/auth/group_schema.py:228
msgid "No such Group."
msgstr "Отсутствует такая группа."

#: ../common/models/authentication_directory.py:1106
msgid "Group {} is not synchronized by AD."
msgstr "Группа {} не синхронизирована со службой каталогов."

#: ../common/models/authentication_directory.py:1113
msgid "There is no users to sync."
msgstr "В группе не найдены пользователи для синхронизации."

#: ../common/models/controller.py:142
msgid "Controller {} has no api client."
msgstr "Контроллер {} не имеет подключения к ECP VeiL."

#: ../common/models/controller.py:148
msgid "ECP VeiL version could not be obtained. Check your token."
msgstr "Не удается получить версию ECP VeiL. Проверьте свой токен."

#: ../common/models/controller.py:156
msgid "ECP VeiL version should be 4.3 or higher. Current version is incompatible."
msgstr "Версия ECP VeiL должна быть 4.3 или выше. Текущая версия не поддерживается."

#: ../common/models/controller.py:188
msgid "Controller {} added."
msgstr "Контроллер {} добавлен."

#: ../common/models/controller.py:244
msgid "Controller {} has been successfully updated."
msgstr "Контроллер {} успешно обновлен."

#: ../common/models/controller.py:248
msgid "Controller {} update failed."
msgstr "Ошибка обновления контроллера {}."

#: ../common/models/controller.py:277
msgid "Controller {} has been removed."
msgstr "Контроллер {} удалён."

#: ../common/models/controller.py:309
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: ../common/models/controller.py:332 ../common/models/controller.py:359
msgid "Controller {} status has been switched to {}."
msgstr "Статус контроллера {} изменен на {}."

#: ../common/models/event.py:74
msgid "Journal in this period is empty."
msgstr "Журнал для этого периода пуст."

#: ../common/models/event.py:91
msgid "Path {} is incorrect."
msgstr "Неверный путь: {}."

#: ../common/models/event.py:94
msgid "Check date. Interval {} - {} is incorrect."
msgstr "Проверьте дату. Некорректный промежуток {} - {}."

#: ../common/models/event.py:99
msgid "Not enough free space."
msgstr "Недостаточно свободного места."

#: ../common/models/event.py:101
msgid "Journal export error."
msgstr "Ошибка экспорта журнала."

#: ../common/models/event.py:240
msgid "Choose right period."
msgstr "Выберите правильный период."

#: ../common/models/event.py:246
msgid "Count must be more than 1."
msgstr "Количество должно быть больше 1."

#: ../common/models/event.py:250
msgid "Journal settings changed."
msgstr "Настройки журнала изменены."

#: ../common/models/pool.py:218
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/models/pool.py:347 ../common/models/pool.py:1760
msgid "Pool {} has been updated."
msgstr "Пул {} обновлен."

#: ../common/models/pool.py:619
msgid "User {} has been included to pool {}."
msgstr "Пользователь {} был включен в пул {}."

#: ../common/models/pool.py:627 ../common/models/vm.py:334
msgid "{} already has permission."
msgstr "{} уже имеет разрешение."

#: ../common/models/pool.py:648
msgid "Removing user {} from pool {}."
msgstr "Удаление пользователя {} из пула {}."

#: ../common/models/pool.py:656
msgid "User {} has no direct right to pool {}."
msgstr "У пользователя {} нет прямых прав на пул {}. Пропускаем."

#: ../common/models/pool.py:684
msgid "Group {} has been included to pool {}."
msgstr "Группа {} включена в пул {}."

#: ../common/models/pool.py:692
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: ../common/models/pool.py:706
msgid "Removing group {} from pool {}."
msgstr "Удаление группы {} из пула {}."

#: ../common/models/pool.py:752
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: ../common/models/pool.py:787
msgid "Delete VMs for GuestPool {}."
msgstr "Удаление виртуальных машин для гостевого пула {}."

#: ../common/models/pool.py:792
msgid "Delete VMs for AutomatedPool {}."
msgstr "Удаление виртуальных машин для автоматического пула {}."

#: ../common/models/pool.py:799
msgid "VM {} has been removed from ECP VeiL."
msgstr "ВМ {} удалена из ECP VeiL."

#: ../common/models/pool.py:825
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: ../common/models/pool.py:858
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: ../common/models/pool.py:875
msgid "Pool {} status changed to {}."
msgstr "Статус пула {} изменен на {}."

#: ../common/models/pool.py:1059 ../web_app/journal/schema.py:285
msgid "The sort parameter is incorrect."
msgstr "Неверный параметр сортировки."

#: ../common/models/pool.py:1070
msgid "List of VM should not be empty."
msgstr "Список виртуальных машин не должен быть пустым."

#: ../common/models/pool.py:1087
msgid "VM doesn't belong to specified pool."
msgstr "Виртуальная машина не принадлежит заданному пулу."

#: ../common/models/pool.py:1098
msgid "VM {} has been removed from the pool {} and ECP VeiL."
msgstr "ВМ {} удалена из пула {} и из ECP VeiL."

#: ../common/models/pool.py:1102
msgid "VM {} has been removed from the pool {}."
msgstr "ВМ {} удалена из пула {}."

#: ../common/models/pool.py:1171
#, python-brace-format
msgid "Tag {name} created for pool {name}."
msgstr "Тэг {name} добавлен к пулу {name}."

#: ../common/models/pool.py:1191
msgid "Tag {} removed from ECP VeiL."
msgstr "Тэг {} удален из ECP VeiL."

#: ../common/models/pool.py:1203
#, python-brace-format
msgid "Tag {name} updated for pool {name} and all vms in pool."
msgstr "Тэг {name} обновлен для пула {name} и всех ВМ в пуле."

#: ../common/models/pool.py:1230
msgid "Tag {} removed from VM {}."
msgstr "Тэг {} удален для ВМ {}."

#: ../common/models/pool.py:1245 ../common/models/pool.py:1263
msgid "Tag {} added to VM {}."
msgstr "Тэг {} назначен ВМ {}."

#: ../common/models/pool.py:1339
msgid "RDS pool {} created."
msgstr "Пул приложений {} создан."

#: ../common/models/pool.py:1463 ../common/models/pool.py:1466
#: ../common/models/pool.py:1945
msgid "VM {} created."
msgstr "ВМ {} создана."

#: ../common/models/pool.py:1467 ../common/models/pool.py:1947
msgid "VM {} created and added to the pool {}."
msgstr "ВМ {} создана и добавлена в пул {}."

#: ../common/models/pool.py:1478
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: ../common/models/pool.py:1653
msgid "Initial_size: {}, total_size: {}, increase_step {}, reserve_size {}."
msgstr "Начальный размер: {}, Максимальный размер: {}, Шаг расширения: {}, Резервный размер: {}."

#: ../common/models/pool.py:1657
msgid "GuestPool {} is created."
msgstr "Создан гостевой пул {}."

#: ../common/models/pool.py:1664
msgid "AutomatedPool {} is created."
msgstr "Создан автоматический пул {}."

#: ../common/models/pool.py:1717 ../common/models/pool.py:1750
msgid "Update Pool {} values."
msgstr "Обновление значений пула {}."

#: ../common/models/pool.py:1846
msgid "There is no client for pool {}."
msgstr "Пул {} не имеет подключения к ECP VeiL. Проверьте контроллер."

#: ../common/models/pool.py:1886
msgid "VM creation task {} finished with error."
msgstr "Задача {} создания ВМ завершилась с ошибкой."

#: ../common/models/pool.py:1907
msgid "Fail to cancel VM creation task."
msgstr "Ошибка отмены задачи создания ВМ."

#: ../common/models/pool.py:1999
msgid "VM creation error."
msgstr "Ошибка создания ВМ."

#: ../common/models/pool.py:2012
msgid "{} vm(s) are successfully added in the {} pool."
msgstr "{} ВМ успешно добавлены в пул {}."

#: ../common/models/pool.py:2017
msgid "Adding VM to the pool {} finished with errors."
msgstr "Добавление ВМ в пул {} закончилось с ошибками."

#: ../common/models/pool.py:2020
msgid "Required: {}, created: {}."
msgstr "Необходимо: {}, создано: {}."

#: ../common/models/settings.py:35
msgid "Settings changed."
msgstr "Настройки изменены."

#: ../common/models/settings.py:63
msgid "Smtp settings are changed."
msgstr "Настройки SMTP сервера изменены."

#: ../common/models/vm.py:153
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: ../common/models/vm.py:179 ../common/models/vm.py:273
#: ../web_app/thin_client_api/handlers.py:453
#: ../web_app/thin_client_api/handlers.py:483
msgid "VM has no api client."
msgstr "ВМ не имеет клиента. Проверьте состояние контроллера."

#: ../common/models/vm.py:202
msgid "Failed to create multi-delete task."
msgstr "Не удалось создать задачу множественного удаления."

#: ../common/models/vm.py:221 ../common/models/vm.py:286
msgid "VM deletion task {} finished with error."
msgstr "Задача {} удаления ВМ завершилась с ошибкой."

#: ../common/models/vm.py:237
msgid "VM multi-deletion task finished with error. Please see task details on VeiL ECP."
msgstr "Задача множественного удаления ВМ завершена с ошибкой. Пожалуйста посмотрите детали задачи на VeiL ECP."

#: ../common/models/vm.py:238
msgid "VMs: {}."
msgstr "ВМ: {}."

#: ../common/models/vm.py:291
msgid "VM {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: ../common/models/vm.py:299
msgid "VM {} deletion task finished with error."
msgstr "Задача удаления ВМ {} завершилась с ошибкой."

#: ../common/models/vm.py:326
msgid "User {} has been included to VM {}."
msgstr "За пользователем {} закреплена ВМ {}."

#: ../common/models/vm.py:355
msgid "VM {} is clear from {} users."
msgstr "ВМ {} освобождена от {} пользователя(-ей)."

#: ../common/models/vm.py:362 ../common/models/vm.py:942
msgid "VM {} is clear from users."
msgstr "ВМ {} освобождена от пользователей."

#: ../common/models/vm.py:452 ../common/models/vm.py:709
msgid "There is no client for controller {}."
msgstr "Контролер {} не имеет подключения к ECP VeiL."

#: ../common/models/vm.py:521
msgid "Not enough free space on data pool."
msgstr "Недостаточно свободного места в пуле данных."

#: ../common/models/vm.py:526
msgid "Possibly blocked by active task on ECP. Wait before next try."
msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."

#: ../common/models/vm.py:554
msgid "VM {} deleting cancelled by timeout."
msgstr "Удаление ВМ {} отменено по таймауту."

#: ../common/models/vm.py:579
msgid "VM multi-deletion task cancelled by timeout. Please see task details on VeiL ECP."
msgstr "Задача множественного удаления ВМ отменена по истечении времени ожидания. Пожалуйста посмотрите детали задачи на VeiL ECP."

#: ../common/models/vm.py:641 ../web_app/controller/schema.py:480
#: ../web_app/journal/schema.py:307
msgid "No such event."
msgstr "Нет такого события."

#: ../common/models/vm.py:725
msgid "Remote task finished with error. Check ECP VeiL."
msgstr "Удаленная задача завершена с ошибкой. Проверьте ECP VeiL."

#: ../common/models/vm.py:740
msgid "VM {} is powered."
msgstr "ВМ {} включена."

#: ../common/models/vm.py:753
msgid "VM can`t be powered on or already powered."
msgstr "ВМ не включается или уже включена."

#: ../common/models/vm.py:760
msgid "VM {} already shutdown."
msgstr "ВМ {} уже выключена."

#: ../common/models/vm.py:769
msgid "VM {} is force shutdown."
msgstr "ВМ {} принудительно выключена."

#: ../common/models/vm.py:775
msgid "VM {} is shutdown."
msgstr "ВМ {} выключена."

#: ../common/models/vm.py:786 ../common/models/vm.py:821
msgid "VM {} is shutdown. Please power this."
msgstr "ВМ {} выключена. Пожалуйста включите её."

#: ../common/models/vm.py:796
msgid "VM {} was force reboot."
msgstr "ВМ {} принудительно перезагружена."

#: ../common/models/vm.py:802
msgid "VM {} was reboot."
msgstr "ВМ {} перезагружена."

#: ../common/models/vm.py:814
msgid "VM {} is suspended."
msgstr "ВМ {} приостановлена."

#: ../common/models/vm.py:834
msgid "Forbid create backup from a thin clone: {}."
msgstr "Запрещено создание резервной копии от тонкого клона: {}."

#: ../common/models/vm.py:846 ../pool_worker/pool_tasks.py:601
msgid "Creating backup finished with error."
msgstr "Создание резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:849
msgid "Backup for VM {} is created."
msgstr "Создана резервная копия для ВМ {}."

#: ../common/models/vm.py:906
msgid "Total size of pool {} increased."
msgstr "Увеличен максимальный размер пула {}."

#: ../common/models/vm.py:920 ../web_app/pool/schema.py:991
msgid "VM {} has been added to the pool {}."
msgstr "ВМ {} добавлена в пул {}."

#: ../common/models/vm.py:953
msgid "Backup restore finished with error."
msgstr "Восстановление из резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:956
msgid "Backup from VM {} restored to pool {} as {}."
msgstr "Резервная копия для ВМ {} восстановлена в пул {} с именем {}."

#: ../common/models/vm.py:983
msgid "VM {} remote access enabled."
msgstr "Удаленный доступ ВМ {} включен."

#: ../common/models/vm.py:992
msgid "Waiting Qemu guest agent for vm {}."
msgstr "Ожидание ответа Гостевого агента для ВМ {}."

#: ../common/models/vm.py:1011
msgid "Can`t set verbose name."
msgstr "Can`t set verbose name."

#: ../common/models/vm.py:1047
msgid "VM {} hostname setting task failed."
msgstr "Ошибка задания hostname ВМ {}."

#: ../common/models/vm.py:1052
msgid "VM {} hostname setting success."
msgstr "ВМ {} успешно задан hostname."

#: ../common/models/vm.py:1121
msgid "VM {} has been prepared."
msgstr "ВМ {} подготовлена."

#: ../common/models/vm.py:1124
msgid "VM preparation task finished with errors. Check ECP Veil."
msgstr "Задача подготовки ВМ завершена с ошибкой. Проверьте ECP VeiL."

#: ../common/models/vm.py:1126
msgid "ECP Veil failed to prepare VM."
msgstr "Не удалось подготовить ВМ на ECP VeiL."

#: ../common/models/vm.py:1145
msgid "{} preparation cancelled by timeout."
msgstr "подготовка {} отменена по таймауту."

#: ../common/models/vm.py:1157
msgid "VM {} preparation error."
msgstr "Ошибка подготовки ВМ {}."

#: ../common/veil/auth/veil_jwt.py:50 ../common/veil/auth/veil_jwt.py:82
msgid "Token expired."
msgstr "Срок действия токена истек."

#: ../common/veil/auth/veil_jwt.py:77
msgid "Token invalid."
msgstr "Недействительный токен."

#: ../common/veil/auth/veil_jwt.py:139
msgid "Error with JWT decode."
msgstr "Ошибка JWT декодирования."

#: ../common/veil/auth/veil_jwt.py:149 ../common/veil/auth/veil_jwt.py:151
#: ../common/veil/auth/veil_jwt.py:153
msgid "Invalid authorization header."
msgstr "Неправильный заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:157
msgid "Missing authorization header."
msgstr "Пропущен заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:193 ../common/veil/veil_handlers.py:63
#: ../common/veil/veil_handlers.py:97
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: ../common/veil/veil_api.py:155
msgid "Can`t find VM {} on VeiL ECP."
msgstr "Не удалось найти ВМ {} на VeiL ECP."

#: ../common/veil/veil_api.py:166
msgid "Can`t find Tag {} on VeiL ECP."
msgstr "Не удалось найти Тег {} на VeiL ECP."

#: ../common/veil/veil_api.py:189
msgid "VeiL ECP {} request error."
msgstr "Ошибка запроса ECP VeiL {}."

#: ../common/veil/veil_decorators.py:43 ../common/veil/veil_decorators.py:49
#: ../web_app/auth/license/handlers.py:36 ../web_app/tests/test_auth_v2.py:116
msgid "Invalid permissions."
msgstr "Недостаточно прав."

#: ../common/veil/veil_decorators.py:44
msgid "IP: {}. username: {}."
msgstr "IP: {}. Пользователь: {}."

#: ../common/veil/veil_errors.py:155
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: ../common/veil/veil_errors.py:160
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: ../common/veil/veil_gino.py:81
msgid "Incorrect sort parameter {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/veil/veil_gino.py:91
msgid "Incorrect request parameter {}."
msgstr "Неверный параметр запроса {}."

#: ../common/veil/veil_gino.py:225
msgid "{} {} has been disabled."
msgstr "{} {} деактивирована."

#: ../common/veil/veil_gino.py:227
msgid "{} {} has`t been found in ECP VeiL. Switched to FAILED."
msgstr "{} {} не найдена на ECP VeiL. Переключена в статус с ошибкой."

#: ../common/veil/veil_gino.py:240
msgid "Group {} has been deleted."
msgstr "Группа {} удалена."

#: ../common/veil/veil_gino.py:244
msgid "Soft_delete exception: {}."
msgstr "Ошибка удаления: {}."

#: ../common/veil/veil_handlers.py:102
msgid "There is no pool with id: {}."
msgstr "Отсутствует пул с id: {}."

#: ../common/veil/veil_handlers.py:106
msgid "User {} has no VM on pool {}."
msgstr "У пользователя {} нет виртуальной машины в пуле {}."

#: ../common/veil/veil_handlers.py:160
msgid "Ws write error."
msgstr "Ошибка записи WS."

#: ../common/veil/veil_redis.py:298
msgid "Redis task waiting exception."
msgstr "Ошибка redis-задачи."

#: ../common/veil/veil_validators.py:30
msgid "Field \"{}\" - {}."
msgstr "Поле \"{}\" - {}."

#: ../monitor_worker/resources_monitor.py:100
msgid "{} is connected: {}."
msgstr "{} подключен: {}."

#: ../monitor_worker/resources_monitor.py:159
msgid "Resource monitor can`t connect to controller {}."
msgstr "Монитор ресурсов не может подключиться к контроллеру {}."

#: ../monitor_worker/resources_monitor.py:186
msgid "Closing ws connection {}."
msgstr "Закрываем WS соединение {}."

#: ../monitor_worker/resources_monitor_manager.py:64
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}."
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: ../monitor_worker/resources_monitor_manager.py:75
msgid "{}: Started."
msgstr "{}: Запущен."

#: ../monitor_worker/resources_monitor_manager.py:92
#, python-brace-format
msgid "{cls}: Controller {name} is already monitored."
msgstr "{cls}: Контроллер {name} уже отслеживается."

#: ../monitor_worker/resources_monitor_manager.py:100
#, python-brace-format
msgid "{cls}: resource monitor for controller {name} connected."
msgstr "{cls}: монитор ресурсов для контроллера {name} подключен."

#: ../pool_worker/pool_task_manager.py:65
msgid "Can`t launch task."
msgstr "Нет такого задания."

#: ../pool_worker/pool_task_manager.py:247
msgid "Task failed to start."
msgstr "Не удалось запустить задачу."

#: ../pool_worker/pool_tasks.py:94
msgid "Task '{}' started."
msgstr "Задача '{}' начала выполнение."

#: ../pool_worker/pool_tasks.py:99
msgid "Task '{}' finished successfully."
msgstr "Задача '{}' завершилась успешно."

#: ../pool_worker/pool_tasks.py:104
msgid "Task '{}' cancelled."
msgstr "Задача '{}' отменена."

#: ../pool_worker/pool_tasks.py:109
msgid "Task '{}' failed."
msgstr "Задача '{}' завершилась с ошибками."

#: ../pool_worker/pool_tasks.py:177
msgid "Creation of pool {}."
msgstr "Создание пула {}."

#: ../pool_worker/pool_tasks.py:201
msgid "Pool Creation cancelled."
msgstr "Создание пула отменено."

#: ../pool_worker/pool_tasks.py:206
msgid "Failed to init pool."
msgstr "Ошибка инициализации пула."

#: ../pool_worker/pool_tasks.py:226
msgid "Pool initialization VM(s) preparation error."
msgstr "В момент инициализации пула подготовка виртуальных машин завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:252
msgid "Expanding of pool {}."
msgstr "Расширение пула {}."

#: ../pool_worker/pool_tasks.py:301 ../pool_worker/pool_tasks.py:378
msgid "VM creating error."
msgstr "Ошибка создания ВМ."

#: ../pool_worker/pool_tasks.py:325 ../pool_worker/pool_tasks.py:402
msgid "VM preparation error."
msgstr "Ошибка подготовки ВМ."

#: ../pool_worker/pool_tasks.py:344
msgid "Automatic recreation of VM {} in the guest pool."
msgstr "Автоматическое пересоздание ВМ {} в гостевом пуле."

#: ../pool_worker/pool_tasks.py:417
msgid "Decreasing of pool {}."
msgstr "Уменьшение пула {}."

#: ../pool_worker/pool_tasks.py:453
msgid "Deleting of pool {}."
msgstr "Удаление пула {}."

#: ../pool_worker/pool_tasks.py:504
msgid "Preparation of vm {}."
msgstr "Подготовка ВМ {}."

#: ../pool_worker/pool_tasks.py:510
msgid "Another task works on this VM."
msgstr "ВМ заблокирована выполнением другой задачи."

#: ../pool_worker/pool_tasks.py:548
msgid "ECP VeiL domain request error."
msgstr "Ошибка запроса ВМ на ECP VeiL."

#: ../pool_worker/pool_tasks.py:551
msgid "Task has`t been created."
msgstr "Задача не была создана."

#: ../pool_worker/pool_tasks.py:568
msgid "VM remote access task {} for VM {} finished with error."
msgstr "Задача {} удаленного доступа к ВМ {} завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:585
msgid "Backup of {}."
msgstr "Бэкап {}."

#: ../pool_worker/pool_tasks.py:598
msgid "Wrong entity type."
msgstr "Неверный тип сущности."

#: ../pool_worker/pool_tasks.py:616
msgid "Removal of VMs from pool {}."
msgstr "Удаление ВМ из пула {}."

#: ../pool_worker/pool_tasks.py:629
msgid "Unsupported pool type."
msgstr "Неподдерживаемый тип пула."

#: ../pool_worker/vm_manager.py:109
msgid "Keep vms on task error."
msgstr "Сохранить ВМ при ошибке задачи."

#: ../pool_worker/vm_manager.py:147
msgid "Synchronize vm data task error."
msgstr "Ошибка задачи синхронизации данных виртуальной машины."

#: ../pool_worker/vm_manager.py:200
msgid "Action upon user disconnect completed. Action: {}. VM: {}. Result: {}."
msgstr "Действие при отключении пользователя завершено. Действие: {}. ВМ: {}. Результат: {}."

#: ../pool_worker/vm_manager.py:206
msgid "Vm post disconnect action error."
msgstr "Ошибка действия ВМ после отключения."

#: ../pool_worker/vm_manager.py:266
msgid "_do_actions_when_user_disconnects_from_vm error."
msgstr "Ошибка _do_actions_when_user_disconnects_from_vm."

#: ../web_app/app.py:125
msgid "VDI broker stopped."
msgstr "VDI брокер остановлен."

#: ../web_app/app.py:137
msgid "{} instance(s) of VDI broker web application launched on {}."
msgstr "Веб-приложение брокера VDI запущено в {} экземпляре(ах) на машине {}."

#: ../web_app/app.py:141
msgid "Authentication system is disabled."
msgstr "Система аутентификации выключена."

#: ../web_app/app.py:145
msgid "The license is expired on {}. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла на машине {}. Некоторые функции будут заблокированы. Свяжитесь с вашим поставщиком."

#: ../web_app/app.py:149
msgid "DEBUG mode is enabled."
msgstr "Режим отладки включен."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:33
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:215
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:271
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:440
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:458
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:474
msgid "No such Authentication Directory."
msgstr "Такая Authentication Directory отсутствует."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:39
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на службу каталогов должна начинаться с ldap(s)://."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:46
msgid "Verbose name should not be empty."
msgstr "Имя не должно быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:53
msgid "Value should be 1-63 latin characters, -, . or _."
msgstr "Значение должно быть в диапазоне от 1-63 латинских символа, -, . или _."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:74
#: ../web_app/auth/group_schema.py:48
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:76
msgid "groups list is empty."
msgstr "Список групп пуст."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:83
msgid "No such mapping."
msgstr "Нет такого отображения."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:88
msgid "DC should not be empty."
msgstr "Класс объекта домена не должен быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:211
msgid "Specify id."
msgstr "Укажите id."

#: ../web_app/auth/group_schema.py:26 ../web_app/auth/group_schema.py:145
msgid "No such group."
msgstr "Отсутствует такая группа."

#: ../web_app/auth/group_schema.py:34
msgid "verbose name must be <= 128 characters."
msgstr "имя должно быть <= 128 символов."

#: ../web_app/auth/group_schema.py:35
msgid "verbose_name is empty."
msgstr "имя пустое."

#: ../web_app/auth/group_schema.py:50
msgid "users list is empty."
msgstr "список пользователей пуст."

#: ../web_app/auth/group_schema.py:56
msgid "Description length must be <= 255 characters."
msgstr "Описание должно быть <= 255 символам."

#: ../web_app/auth/group_schema.py:176
msgid "Group {} already exists."
msgstr "Группа {} уже существует."

#: ../web_app/auth/group_schema.py:218
msgid "Specify Group.id or Group.ad_guid."
msgstr "Укажите Group.id или Group.ad_guid."

#: ../web_app/auth/group_schema.py:220
msgid "Specify Group.id or Group.ad_guid. Not both."
msgstr "Укажите Group.id или Group.ad_guid. Не оба."

#: ../web_app/auth/handlers.py:26
msgid "Missing request body."
msgstr "Отсутствует тело запроса."

#: ../web_app/auth/handlers.py:28
msgid "Missing username and password."
msgstr "Отсутствует имя пользователя и пароль."

#: ../web_app/auth/handlers.py:38
msgid "Missing username."
msgstr "Отсутствует имя пользователя."

#: ../web_app/auth/handlers.py:40
msgid "Missing password."
msgstr "Отсутствует пароль."

#: ../web_app/auth/handlers.py:52
msgid "External auth system is disabled. Check broker settings."
msgstr "Внешняя служба авторизации отключена. Проверьте настройки брокера."

#: ../web_app/auth/handlers.py:56
msgid "PAM or LOCAL auth only. Check broker settings."
msgstr "Проверьте настройки брокера. Разрешена только pam ИЛИ локальная авторизация."

#: ../web_app/auth/handlers.py:66
msgid "Auth system is disabled. Check broker settings."
msgstr "Проверьте настройки брокера. Система аутентификации отключена."

#: ../web_app/auth/handlers.py:76 ../web_app/thin_client_api/handlers.py:364
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: ../web_app/auth/handlers.py:99 ../web_app/auth/handlers.py:118
msgid "Authentication failed for user: {}."
msgstr "Ошибка авторизации пользователя: {}."

#: ../web_app/auth/handlers.py:134
msgid "User {} logged out."
msgstr "Пользователь {} вышел из системы."

#: ../web_app/auth/license/handlers.py:51
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: ../web_app/auth/license/handlers.py:62
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: ../web_app/auth/license/handlers.py:69
msgid "Try to upload invalid license key."
msgstr "Неудачная попытка загрузить лицензионный ключ."

#: ../web_app/auth/license/handlers.py:72
msgid "Valid license key is uploaded."
msgstr "Лицензионный ключ загружен."

#: ../web_app/auth/user_schema.py:30 ../web_app/auth/user_schema.py:272
#: ../web_app/thin_client_api/schema.py:271
msgid "No such user."
msgstr "Нет такого пользователя."

#: ../web_app/auth/user_schema.py:48
msgid "username must contain letters, digits, _, +, begin from letter and can't contain any spaces."
msgstr "имя пользователя должно состоять из букв, цифр, _, +, начинаться с буквы и не содержать пробелов."

#: ../web_app/auth/user_schema.py:57
msgid "Email {} is already busy."
msgstr "Email {} занят."

#: ../web_app/auth/user_schema.py:70
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: ../web_app/auth/user_schema.py:84
msgid "Password must contain letters and/or digits, special characters; also be at least 8 characters."
msgstr "Пароль должен содержать разнорегистровые буквы и/или цифры, специальные символы; также должен быть не менее 8 символов."

#: ../web_app/auth/user_schema.py:89
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: ../web_app/auth/user_schema.py:95
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: ../web_app/auth/user_schema.py:268
msgid "Specify id or username."
msgstr "Укажите id или имя пользователя."

#: ../web_app/auth/user_schema.py:512
msgid "Can`t remove permission(s) {} because they are granted to groups of user {}."
msgstr "Невозможно удалить разрешения {}, так как они выданы группам, в которых состоит пользователь."

#: ../web_app/controller/resource_schema.py:375
msgid "{} is unreachable on ECP VeiL."
msgstr "{} недоступен на ECP VeiL."

#: ../web_app/controller/resource_schema.py:703 ../web_app/pool/schema.py:1825
msgid "Cant create CD-ROM for powered domain {}."
msgstr "Невозможно создать CD-ROM для включенной виртуальной машины {}."

#: ../web_app/controller/resource_schema.py:712 ../web_app/pool/schema.py:1834
msgid "Creating a CD-ROM on the virtual machine {}."
msgstr "Создание CD-ROM на виртуальной машине {}."

#: ../web_app/controller/schema.py:35
msgid "name can`t be empty."
msgstr "имя не может быть пустым."

#: ../web_app/controller/schema.py:44
msgid "name `{}` is busy."
msgstr "имя `{}` уже используется."

#: ../web_app/controller/schema.py:52
msgid "address can`t be empty."
msgstr "адресс не может быть пустым."

#: ../web_app/controller/schema.py:61
msgid "address `{}` is busy."
msgstr "адресс `{}` уже используется."

#: ../web_app/controller/schema.py:68
msgid "token can`t be empty."
msgstr "токен не может быть пустым."

#: ../web_app/controller/schema.py:78 ../web_app/pool/schema.py:70
msgid "No such controller."
msgstr "Нет такого контроллера."

#: ../web_app/controller/schema.py:520 ../web_app/controller/schema.py:553
msgid "Connection to ECP has been failed."
msgstr "Соединение с ECP не удалось."

#: ../web_app/front_ws_api/handlers.py:46
msgid "WebSocket opened."
msgstr "WebSocket открыт."

#: ../web_app/front_ws_api/handlers.py:51
msgid "Message: {}."
msgstr "Сообщение: {}."

#: ../web_app/front_ws_api/handlers.py:75
msgid "WS listener error."
msgstr "Ошибка сервиса прослушивания WS."

#: ../web_app/front_ws_api/handlers.py:76
msgid "Unknown subscription source."
msgstr "Неизвестный источник подписки."

#: ../web_app/front_ws_api/handlers.py:93
msgid "Already subscribed."
msgstr "Уже подписан."

#: ../web_app/front_ws_api/handlers.py:100
msgid "Not subscribed."
msgstr "Не подписан."

#: ../web_app/journal/schema.py:415
msgid "Journal is exported."
msgstr "Журнал экспортирован."

#: ../web_app/pool/schema.py:241
msgid "Missing connection spice data."
msgstr "Пропущены данные для spice соединения."

#: ../web_app/pool/schema.py:255
msgid "Missing connection vnc data."
msgstr "Пропущены данные для vnc соединения."

#: ../web_app/pool/schema.py:275 ../web_app/pool/schema.py:755
#: ../web_app/pool/schema.py:776
msgid "No such pool."
msgstr "Нет такого пула."

#: ../web_app/pool/schema.py:286
msgid "Pool name must contain only characters, digits and -."
msgstr "Имя пула должно содержать только буквы, цифры и -."

#: ../web_app/pool/schema.py:302
msgid "Template name of VM must contain only characters, digits, -. Template name length must be in [{} {}] interval."
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, -. Длина шаблонного имени должна быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:313
msgid "Initial number of VM must be in {}-{} interval."
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:337
msgid "Reserve size of VMs can not be more than maximal number of Vms."
msgstr "Резервное число ВМ не может быть больше максимального числа ВМ."

#: ../web_app/pool/schema.py:342
msgid "Reserve size of VM must be in {}-{} interval."
msgstr "Резервное число ВМ должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:371
msgid "Maximal number of created VM can not be less than initial number of VM."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ."

#: ../web_app/pool/schema.py:377
msgid "Maximal number of created VM must be in [{} {}] interval."
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:384
msgid "Maximal number of created VMs can not be less than current amount of Vms."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше текущего числа ВМ."

#: ../web_app/pool/schema.py:403
msgid "Increase step must be positive and less or equal to total_size."
msgstr "Шаг увеличения должен быть положительным и меньше или равен общему количеству."

#: ../web_app/pool/schema.py:407
msgid "Increase step must be less than {}."
msgstr "Шаг увеличения должен быть меньше {}."

#: ../web_app/pool/schema.py:415
msgid "Connection type cannot be empty."
msgstr "Тип подключения не может быть пустым."

#: ../web_app/pool/schema.py:420
msgid "Vm action timeout must be a positive number."
msgstr "Время ожидания действия ВМ должно быть положительным числом."

#: ../web_app/pool/schema.py:430
msgid "Vm disconnect action RECREATE is not allowed for pool type {}."
msgstr "Действие пересоздания ВМ при отключении не разрешено для пула типа {}."

#: ../web_app/pool/schema.py:434
msgid "Guest pool must have vm disconnect action RECREATE."
msgstr "В гостевом пуле должно быть действие пересоздания ВМ при отключении."

#: ../web_app/pool/schema.py:437
msgid "RDS pool is not allowed to have vm disconnect actions."
msgstr "Пул RDS не может иметь действия при отключении ВМ."

#: ../web_app/pool/schema.py:451
msgid "Connection types {} are not supported."
msgstr "Типы подключения {} не поддерживаются."

#: ../web_app/pool/schema.py:623 ../web_app/thin_client_api/handlers.py:263
msgid "VM is unreachable on ECP VeiL."
msgstr "ВМ недоступна на ECP VeiL."

#: ../web_app/pool/schema.py:803
msgid "Pool {} has been restored."
msgstr "Ошибки пула {} сброшены."

#: ../web_app/pool/schema.py:809
msgid "Pool {} is in service mode."
msgstr "Пул {} находится в сервисном режиме."

#: ../web_app/pool/schema.py:813
msgid "Pool {} is already active."
msgstr "Пул {} уже активирован."

#: ../web_app/pool/schema.py:894
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: ../web_app/pool/schema.py:974
msgid "VM {} is already in one of pools."
msgstr "Виртуальная машина {} уже в одном из пулов."

#: ../web_app/pool/schema.py:1043
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:1077
msgid "Failed to update RDS pool {}. Name must be unique."
msgstr "Ошибка редактирования пула приложений {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:1111
msgid "Can not expand pool {} because it reached its total_size."
msgstr "Не удается расширить пул {} т.к. достигнут максимальный размер."

#: ../web_app/pool/schema.py:1125
msgid "Another task works on pool {}: {}."
msgstr "Другая задача выполняется над пулом {}."

#: ../web_app/pool/schema.py:1133
msgid "Increase_step {}."
msgstr "Шаг расширения пула {}."

#: ../web_app/pool/schema.py:1135
msgid "Expansion of pool {} requested."
msgstr "Запрошено расширение пула {}."

#: ../web_app/pool/schema.py:1254
msgid "Failed to create pool {}."
msgstr "Ошибка создания пула {}."

#: ../web_app/pool/schema.py:1318
msgid "Failed to update total_size. Task status is {}. Check journal for more info."
msgstr "Не удалось обновить максимальный размер. Статус задачи: {}. Проверьте журнал для получения дополнительной информации."

#: ../web_app/pool/schema.py:1361
msgid "Failed to update pool {}. Name must be unique."
msgstr "Ошибка редактирования пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:1388
msgid "Settings of pool {} is copied."
msgstr "Настройки пула {} скопированы."

#: ../web_app/pool/schema.py:1526
msgid "There is no VM {}."
msgstr "Нет ВМ {}."

#: ../web_app/pool/schema.py:1538
msgid "Impossible to assign more than 1 user to VM {} in guest pool."
msgstr "Невозможно назначить более 1 пользователя на ВМ {} в гостевом пуле."

#: ../web_app/pool/schema.py:1545 ../web_app/pool/schema.py:1582
msgid "Provide users list or username."
msgstr "Укажите список пользователей или имя пользователя."

#: ../web_app/pool/schema.py:1554
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: ../web_app/pool/schema.py:1621
msgid "Another task works on VM {}."
msgstr "Другая задача выполняется над ВМ {}."

#: ../web_app/pool/schema.py:1778
msgid "Only VM with Windows OS can be in domain."
msgstr "Только ВМ на ОС Windows могут находиться в домене."

#: ../web_app/pool/schema.py:1857 ../web_app/pool/schema.py:1894
msgid "VM {} is powered. Please shutdown this."
msgstr "ВМ {} включена. Пожалуйста выключите её."

#: ../web_app/pool/schema.py:1864 ../web_app/pool/schema.py:1922
msgid "VeiL ECP error: {}."
msgstr "Ошибка запроса ECP VeiL: {}."

#: ../web_app/pool/schema.py:1868
msgid "The template {} change and distribute this changes to thin clones."
msgstr "Шаблон {} изменен и распространен с изменениями на тонкие клоны."

#: ../web_app/pool/schema.py:1906
msgid "Prohibited creating template from the thin clone."
msgstr "Запрещено создание шаблона из тонкого клона."

#: ../web_app/pool/schema.py:1925
msgid "Vm {} has converted to template {}."
msgstr "ВМ {} преобразована в шаблон {}."

#: ../web_app/settings/schema.py:22
msgid "Apache server."
msgstr "Сервер Apache."

#: ../web_app/settings/schema.py:23 ../web_app/settings/schema.py:24
msgid "Database."
msgstr "База данных."

#: ../web_app/settings/schema.py:27
msgid "Monitor worker."
msgstr "Монитор состояния компонентов."

#: ../web_app/settings/schema.py:28
msgid "Task worker."
msgstr "Обработчик задач."

#: ../web_app/settings/schema.py:29
msgid "Web application."
msgstr "Веб-приложение."

#: ../web_app/settings/schema.py:122
msgid "Unable to get services information. {}."
msgstr "Невозможно получить информацию о сервисах. {}."

#: ../web_app/settings/schema.py:126
msgid "No services launched."
msgstr "Никаких сервисов не запущено."

#: ../web_app/settings/schema.py:139
msgid "Output parsing error. {}."
msgstr "Ошибка вывода парсинга. {}."

#: ../web_app/settings/schema.py:274
msgid "Invalid service name {}."
msgstr "Недействительное название службы {}."

#: ../web_app/settings/schema.py:291
msgid "Error occurred during service action executing. {}."
msgstr "Ошибка при выполнении действия сервиса. {}."

#: ../web_app/settings/schema.py:296
msgid "Executed action {} for service {}."
msgstr "Выполнено действие {} для сервиса {}."

#: ../web_app/settings/schema.py:315
msgid "Unable to check status of service {}."
msgstr "Невозможно проверить статус сервиса {}."

#: ../web_app/settings/schema.py:329
msgid "Cache is cleared."
msgstr "Кэш очищен."

#: ../web_app/statistics/schema.py:262
msgid "Pool with id {} does not exist."
msgstr "Пула с id {} не существует."

#: ../web_app/statistics/schema.py:273
msgid "Failed to generate statistics report."
msgstr "Ошибка создания отчета статистики."

#: ../web_app/task/schema.py:104
msgid "No such task."
msgstr "Нет такого задания."

#: ../web_app/task/schema.py:129
msgid "No such task or status of task {} is not {}."
msgstr "Нет такого задания или статус задания {} не {}."

#: ../web_app/task/schema.py:141
msgid "Task '{} ({})' is requested to be cancelled by user {}."
msgstr "Задача '{} ({})' запрошена для отмены пользователем {}."

#: ../web_app/task/schema.py:161
msgid "No controller with id {}."
msgstr "Нет контроллера с id {}."

#: ../web_app/task/schema.py:169
msgid "Tasks associated with controller {} are requested to be cancelled by user {}."
msgstr "Задачи, связанные с контроллером {}, запрошены для отменены пользователем {}."

#: ../web_app/thin_client_api/handlers.py:60
msgid "User {} requested pools data."
msgstr "Пользователь {} запросил список пулов."

#: ../web_app/thin_client_api/handlers.py:105
msgid "Looking for machine."
msgstr "Поиск ВМ."

#: ../web_app/thin_client_api/handlers.py:121
msgid "The pool is busy. Try again in 1 minute."
msgstr "Пул занят. Попробуйте снова через 1 минуту."

#: ../web_app/thin_client_api/handlers.py:139
msgid "The pool doesn`t have free machines. Try again after 5 minutes."
msgstr "В пуле нет свободных машин. Повторите попытку через 5 минут."

#: ../web_app/thin_client_api/handlers.py:142
msgid "The pool doesn`t have free machines."
msgstr "В пуле нет свободных машин."

#: ../web_app/thin_client_api/handlers.py:149
msgid "Machine is being prepared."
msgstr "ВМ подготавливается."

#: ../web_app/thin_client_api/handlers.py:154
msgid "User {} connected to pool {}."
msgstr "Пользователь {} подключился к пулу {}."

#: ../web_app/thin_client_api/handlers.py:161
msgid "Connection data resolving (address/port)."
msgstr "Получение данных подключения (адрес/порт)."

#: ../web_app/thin_client_api/handlers.py:175
msgid "Unable to get list of published applications. {}."
msgstr "Невозможно получить список опубликованных приложений. {}."

#: ../web_app/thin_client_api/handlers.py:211
msgid "The remote controller is unavailable."
msgstr "Контроллер недоступен."

#: ../web_app/thin_client_api/handlers.py:223
msgid "The controller didn`t provide a VM address. Try again in 1 minute."
msgstr "Контроллер не передал адрес ВМ. Попробуйте снова через 1 минуту."

#: ../web_app/thin_client_api/handlers.py:266
msgid "Controller did not reply. Check if it is available."
msgstr "Контроллер не ответил. Проверьте, доступен ли он."

#: ../web_app/thin_client_api/handlers.py:276
msgid "Setting time zone."
msgstr "Настройки временной зоны."

#: ../web_app/thin_client_api/handlers.py:325
msgid "Failed to set time zone for vm {}."
msgstr "Ошибка установки временной зоны для ВМ {}."

#: ../web_app/thin_client_api/handlers.py:345
msgid "VM address resolving. Attempt number {}."
msgstr "Получение адреса ВМ. Попытка номер {}."

#: ../web_app/thin_client_api/handlers.py:367
msgid "Pool not found."
msgstr "Пул не найден."

#: ../web_app/thin_client_api/handlers.py:376
msgid "The pool doesnt support connection type {}."
msgstr "Пул не поддерживает тип соединения {}."

#: ../web_app/thin_client_api/handlers.py:420
msgid "User {} executed action {} on VM {}."
msgstr "Пользователь {} выполнил действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:422
msgid "User {} failed to execute action {} on VM {}."
msgstr "Пользователю {} не удалось выполнить действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:507
msgid "Message can not be empty."
msgstr "Сообщение не может быть пустым."

#: ../web_app/thin_client_api/handlers.py:528
msgid "Wrong message format."
msgstr "Неправильны формат сообщения."

#: ../web_app/thin_client_api/handlers.py:623
msgid "Ws: on_message: error."
msgstr "Ws: on_message: ошибка."

#: ../web_app/thin_client_api/handlers.py:803
msgid "VM {} is not registered in VDI broker."
msgstr "ВМ {} не зарегистрирована в брокере VDI."

#: ../web_app/thin_client_api/schema.py:168
msgid "No connection information with id {}."
msgstr "Нет информации о подключении с id {}."

#: ../web_app/thin_client_api/schema.py:262
msgid "All connections."
msgstr "Все подключения."

#: ../web_app/thin_client_api/schema.py:265
msgid "Connection id: {}."
msgstr "id подключения: {}."

#: ../web_app/thin_client_api/schema.py:272
msgid "Connections of user: {}."
msgstr "Подключения пользователя {}."

#: ../web_app/thin_client_api/schema.py:276
msgid "Thin client disconnect requested."
msgstr "Запрошено отключение тонкого клиента."

#: ../web_app/thin_client_api/schema.py:313
msgid "User {} does not exist."
msgstr "Не существует пользователя {}."

#~ msgid "VM {} failed to receive DHCP ip address ({})."
#~ msgstr "ВМ {} не получила IP адрес по DHCP ({})."

#~ msgid "VM {} domain including task failed."
#~ msgstr "Ошибка включения ВМ {} в домен."

#~ msgid "VM {} AD inclusion success."
#~ msgstr "ВМ {} успешно заведена в AD."

#~ msgid "VM {} AD inclusion skipped."
#~ msgstr "Заведение ВМ {} в домен пропущено."

#~ msgid "VM {} has been not prepared."
#~ msgstr "ВМ {} не подготовлена."

#~ msgid "Check pool settings."
#~ msgstr "Проверьте настройки пула."

#~ msgid "Password {} contains invalid characters."
#~ msgstr "Пароль {} содержит недопустимые символы."

#~ msgid "username {} must contain >= 3 chars (letters, digits, _, -, +), begin from letter and can't contain any spaces."
#~ msgstr "имя пользователя {} должно быть >= 3 символов (буквы, цифры, _, -, +), начинаться с буквы и не содержать пробелов."

#~ msgid "Redis waiting exception."
#~ msgstr "Ошибка Redis."

#~ msgid "User {} password setting error."
#~ msgstr "Ошибка задания пароля пользователя {}."

#~ msgid "Another task works on pool {} before creating new blank VM."
#~ msgstr "Другая задача выполняется над пулом {} перед созданием новой пустой ВМ."

#~ msgid "Expansion of guest pool {} requested."
#~ msgstr "Запрошено расширение гостевого пула {}."

#~ msgid "Active directory object has no service username or password. Including skipped."
#~ msgstr "У службы каталогов не указаны имя пользователя и пароль. Пропускаем."

#~ msgid "VM {} active directory group including error."
#~ msgstr "Ошибка ввода ВМ {} в группу AD."

#~ msgid "VM {} AD group including successful."
#~ msgstr "ВМ {} успешно заведена в контейнер/группу AD."

#~ msgid "Demo version."
#~ msgstr "Демонстрационная версия."

#~ msgid "Update Pool values for AutomatedPool {}."
#~ msgstr "Обновление значений пула для автоматического пула {}."

#~ msgid "Failed to create automated pool {}."
#~ msgstr "Ошибка создания автоматического пула {}."

#~ msgid "Failed to update automated pool {}. Name must be unique."
#~ msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#~ msgid "ECP VeiL controller {} error."
#~ msgstr "Ошибка контроллера ECP VeiL {}."

#~ msgid "Critical controller error."
#~ msgstr "Критическая ошибка контроллера."

#~ msgid "Role {} has been set to pool {}."
#~ msgstr "Роль {} добавлена в пул {}."

#~ msgid "Pool already has role."
#~ msgstr "Пул уже имеет роль."

#~ msgid "Roles: {} was deleted to pool {}."
#~ msgstr "Роли: {} удалены в пуле {}."

#~ msgid "Controller can`t create VM. Unknown node."
#~ msgstr "Контроллер не может создать ВМ. Неизвестный узел."

#~ msgid "Unknown node {}."
#~ msgstr "Неизвестный узел {}."

#~ msgid "Attempts to create VM {} have been exhausted."
#~ msgstr "Превышен лимит попыток создания ВМ {}."

#~ msgid "  Duration: {}."
#~ msgstr "  Продолжительность: {}."

#~ msgid "User {} created with role {}."
#~ msgstr "Пользователь {} создан с ролью {}."

#~ msgid "Something went wrong. Interrupt while."
#~ msgstr "Что-то пошло не так. Прерываем while."

#~ msgid "Controller has not free space for creating new VM."
#~ msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#~ msgid "Pool {} has been deactivated."
#~ msgstr "Пул {} деактивирован."

#~ msgid "Can`t connect to {}."
#~ msgstr "Не удается подключиться к {}."

#~ msgid "StaticPool: Create VMs."
#~ msgstr "Статический пул: создание виртуальных машин."

#~ msgid "StaticPool: Create StaticPool."
#~ msgstr "Статический пул: создание статического пула."

#~ msgid "StaticPool: Create Pool."
#~ msgstr "Статический пул: создание пула."

#~ msgid "2fa auth error for user: {}."
#~ msgstr "Ошибка двухфакторной аутентификации для пользователя: {}."

#~ msgid "User {} do not have a secret code for 2fa auth. Please generate this in settings of user."
#~ msgstr "У пользователя {} нет секретного кода для двухфакторной аутентификации. Пожалуйста, сгенерируйте это в настройках пользователя."

#~ msgid "One-time password error for user: {}."
#~ msgstr "Ошибка одноразового пароля для пользователя: {}."

#~ msgid "Group {} is removed for user {}."
#~ msgstr "Группа {} удалена у пользователя {}."
