# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <emil@emil-pc>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-12-22 16:41+0300\n"
"PO-Revision-Date: 2020-07-30 11:25+0300\n"
"Last-Translator: Emil <emil@emil-pc>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:56
#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:270
#: ../common/migrations/versions/ae7bbf17ac03_event.py:51
msgid "Add new journal archive."
msgstr "Добавлен новый архив журнала."

#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:57
#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:271
#: ../common/migrations/versions/ae7bbf17ac03_event.py:52
msgid "Archive name:"
msgstr "Имя архива:"

#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:58
#: ../common/migrations/versions/951435b7a90a_journal_right_archiving.py:272
#: ../common/migrations/versions/ae7bbf17ac03_event.py:53
msgid "path:"
msgstr "путь:"

#: ../common/models/auth.py:138
msgid "Role {} is added to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:143 ../common/models/auth.py:160
msgid "User {} roles: {}."
msgstr "Роли пользователя {}: {}."

#: ../common/models/auth.py:146
msgid "Role {} is assigned to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:153
msgid "Roles: {} was deleted to user {}."
msgstr "Роли: {} удалены у пользователя {}."

#: ../common/models/auth.py:168
msgid "Group {} is removed for user {}."
msgstr "Группа {} удалена у пользователя {}."

#: ../common/models/auth.py:175
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: ../common/models/auth.py:187
msgid "There is no more active superuser."
msgstr "Больше нет активного суперпользователя."

#: ../common/models/auth.py:192
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: ../common/models/auth.py:220
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: ../common/models/auth.py:238
msgid "User {} created with role {}."
msgstr "Пользователь {} создан с ролью {}."

#: ../common/models/auth.py:249
msgid "Values of user {} is changed."
msgstr "Параметры пользователя {} изменены."

#: ../common/models/auth.py:256 ../common/models/auth.py:260
msgid "Roles: {}."
msgstr "Роли: {}."

#: ../common/models/auth.py:257
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал суперпользователем."

#: ../common/models/auth.py:261
#, python-brace-format
msgid "User {username} is no longer a superuser."
msgstr "Пользователь {username} перестал быть суперпользователем."

#: ../common/models/auth.py:278
#, python-brace-format
msgid "User {username} has been logged in."
msgstr "Пользователь {username} вошел в систему."

#: ../common/models/auth.py:279
msgid "Auth type: {}, IP: {}."
msgstr "Тип авторизации: {}, IP: {}."

#: ../common/models/auth.py:296
#, python-brace-format
msgid "User {username} has been logged out."
msgstr "Пользователь {username} вышел из системы."

#: ../common/models/auth.py:394
msgid "Group {} is created."
msgstr "Группа {} создана."

#: ../common/models/auth.py:409
msgid "Values of group {} is updated."
msgstr "Параметры группы {} обновлены."

#: ../common/models/auth.py:423
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: ../common/models/auth.py:427
msgid "User {} is already in group {}."
msgstr "Пользователь {} уже находится в группе {}."

#: ../common/models/auth.py:437
msgid "Removing user {} from group {}."
msgstr "Удаление пользователя {} из группы {}."

#: ../common/models/auth.py:445
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: ../common/models/auth.py:449
msgid "Group {} has already role {}."
msgstr "Группе {} уже назначена роль {}."

#: ../common/models/auth.py:459
msgid "Roles: {} was deleted to group {}."
msgstr "Роли: {} удалены из группы {}."

#: ../common/models/authentication_directory.py:119
#: ../web_app/tests/test_auth_dir.py:125
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной директории авторизации."

#: ../common/models/authentication_directory.py:140
msgid "Authentication directory {} is created."
msgstr "Директория авторизации {} создана."

#: ../common/models/authentication_directory.py:170
msgid "Values for auth directory is updated."
msgstr "Значения для директории авторизации обновлены."

#: ../common/models/authentication_directory.py:197
msgid "Arguments: {} of group: {}."
msgstr "Аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:198
msgid "Mapping for auth directory {} is created."
msgstr "Отображение для директории авторизации {} создано."

#: ../common/models/authentication_directory.py:221
msgid "New arguments: {} of group: {}."
msgstr "Новые аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:222
msgid "Mapping for auth directory {} is updated."
msgstr "Mapping for auth directory {} is updated."

#: ../common/models/authentication_directory.py:244
#: ../common/models/authentication_directory.py:429
msgid "Authentication directory server {} is down."
msgstr "Сервер директории авторизации {} не работает."

#: ../common/models/authentication_directory.py:251
msgid "Authentication directory server {} is connected."
msgstr "Сервер директории авторизации {} подключен."

#: ../common/models/authentication_directory.py:284
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: ../common/models/authentication_directory.py:313
msgid "Mappings: {}."
msgstr "Сопоставления: {}."

#: ../common/models/authentication_directory.py:329
msgid "escaped values: {}."
msgstr "скрытые значения: {}."

#: ../common/models/authentication_directory.py:330
msgid "role mapping value type: {}."
msgstr "тип значений отображения роли: {}."

#: ../common/models/authentication_directory.py:339
msgid "User veil groups: {}."
msgstr "Группы пользователей veil: {}."

#: ../common/models/authentication_directory.py:346
msgid "Attaching user {} to group: {}."
msgstr "Прикрепление пользователя {} к группе {}."

#: ../common/models/authentication_directory.py:359
#: ../common/models/authentication_directory.py:370
msgid "No authentication directory controllers."
msgstr "Нет контроллеров директории авторизации."

#: ../common/models/authentication_directory.py:393
msgid "Invalid credentials (ldap): {}."
msgstr "Неверные учетные данные (ldap): {}."

#: ../common/models/authentication_directory.py:400
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: ../common/models/authentication_directory.py:416
msgid "LDAP username and password can`t be empty."
msgstr "Имя пользователя и пароль LDAP не могут быть пустыми."

#: ../common/models/authentication_directory.py:424
msgid "Authentication directory server {} has bad auth info."
msgstr "Не удалось подключиться к серверу директории авторизации {}."

#: ../common/models/authentication_directory.py:491
#: ../common/models/authentication_directory.py:570
msgid "Fail to connect to Authentication Directory. Check service information."
msgstr "Ошибка подключения к директории авторизации."

#: ../common/models/authentication_directory.py:614
msgid "{} new users synced from Authentication Directory."
msgstr "{} новых пользователей синхронизировано из директории авторизации."

#: ../common/models/authentication_directory.py:622
#: ../web_app/auth/group_schema.py:180
msgid "No such Group."
msgstr "Отсутствует такая группа."

#: ../common/models/authentication_directory.py:624
msgid "Group {} is not synchronized by AD."
msgstr "Группа {} не синхронизированна с директорией авторизации."

#: ../common/models/authentication_directory.py:630
msgid "There is no users to sync."
msgstr "В группе не найдены пользователи для синхронизации."

#: ../common/models/controller.py:132
msgid "Controller {} has no api client."
msgstr "Контроллер {} не имеет подключения к ECP VeiL."

#: ../common/models/controller.py:137
msgid "Veil ECP version could not be obtained. Check your token."
msgstr "Не удается получить версию Veil ECP. Проверьте свой токен."

#: ../common/models/controller.py:144
msgid "Veil ECP version should be 4.3 or higher. Current version is incompatible."
msgstr "Версия Veil ECP должна быть 4.3 или выше. Текущая версия не поддерживается."

#: ../common/models/controller.py:171
msgid "Controller {} added."
msgstr "Контроллер {} добавлен."

#: ../common/models/controller.py:216
msgid "Controller {} has been successfully updated."
msgstr "Контроллер {} успешно обновлен."

#: ../common/models/controller.py:218
msgid "Controller {} update failed."
msgstr "Ошибка обновления контроллера {}."

#: ../common/models/controller.py:242
msgid "Controller {} has been removed."
msgstr "Контроллер {} удалён."

#: ../common/models/controller.py:262
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: ../common/models/controller.py:281
msgid "Controller {} status has been switched to {}."
msgstr "Статус контроллера {} изменен на {}."

#: ../common/models/event.py:201
msgid "Journal settings changed."
msgstr "Настройки журнала изменены."

#: ../common/models/pool.py:156
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/models/pool.py:408
msgid "User {} has been included to pool {}."
msgstr "Пользователь {} был включен в пул {}."

#: ../common/models/pool.py:412 ../common/models/vm.py:166
msgid "{} already has permission."
msgstr "{} уже имеет разрешение."

#: ../common/models/pool.py:426
msgid "Removing user {} from pool {}."
msgstr "Удаление пользователя {} из пула {}."

#: ../common/models/pool.py:431
msgid "User {} has no direct right to pool {}."
msgstr "У пользователя {} нет прямых прав на пул {}. Пропускаем."

#: ../common/models/pool.py:452
msgid "Group {} has been included to pool {}."
msgstr "Группа {} включена в пул {}."

#: ../common/models/pool.py:456
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: ../common/models/pool.py:467
msgid "Removing group {} from pool {}."
msgstr "Удаление группы {} из пула {}."

#: ../common/models/pool.py:497
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: ../common/models/pool.py:520
msgid "Delete VMs for AutomatedPool {}."
msgstr "Удаление виртуальных машин для автоматического пула {}."

#: ../common/models/pool.py:525
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: ../common/models/pool.py:550
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: ../common/models/pool.py:562
msgid "Pool {} has been deactivated."
msgstr "Пул {} деактивирован."

#: ../common/models/pool.py:738
msgid "StaticPool: Create Pool."
msgstr "Статический пул: создание пула."

#: ../common/models/pool.py:746
msgid "StaticPool: Create StaticPool."
msgstr "Статический пул: создание статического пула."

#: ../common/models/pool.py:748
msgid "StaticPool: Create VMs."
msgstr "Статический пул: создание виртуальных машин."

#: ../common/models/pool.py:756 ../common/models/pool.py:1006
msgid "VM {} created."
msgstr "ВМ {} создана."

#: ../common/models/pool.py:758
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: ../common/models/pool.py:773 ../common/models/pool.py:940
msgid "Pool {} has been updated."
msgstr "Пул {} обновлен."

#: ../common/models/pool.py:891
msgid "Initial_size: {}, total_size: {}, increase_step {}, reserve_size {}."
msgstr "Начальный размер: {}, Максимальный размер: {}, Шаг расширения: {}, Резервный размер: {}."

#: ../common/models/pool.py:893
msgid "AutomatedPool {} is created."
msgstr "Создан автоматический пул {}."

#: ../common/models/pool.py:912
msgid "Update Pool values for AutomatedPool {}."
msgstr "Обновление значений пула для автоматического пула {}."

#: ../common/models/pool.py:933
msgid "Update AutomatedPool values for {}."
msgstr "Обновление значений автоматического пула {}."

#: ../common/models/pool.py:950
msgid "There is no client for pool {}."
msgstr "Пул {} не имеет подключения к ECP VeiL. Проверьте контроллер."

#: ../common/models/pool.py:981
msgid "VM creation task {} finished with error."
msgstr "Задача {} создания ВМ завершилась с ошибкой."

#: ../common/models/pool.py:990
msgid "Fail to cancel VM creation task."
msgstr "Ошибка отмены задачи создания ВМ."

#: ../common/models/pool.py:1007
msgid "VM {} created and added to the pool {}."
msgstr "ВМ {} создана и добавлена в пул {}."

#: ../common/models/pool.py:1015
msgid "Attempts to create VM {} have been exhausted."
msgstr "Превышен лимит попыток создания ВМ {}."

#: ../common/models/pool.py:1046
msgid "VM creation error."
msgstr "Ошибка создания ВМ."

#: ../common/models/pool.py:1050
msgid "{} vm(s) are successfully added in the {} pool."
msgstr "{} ВМ успешно добавлены в пул {}."

#: ../common/models/pool.py:1053
msgid "Adding VM to the pool {} finished with errors."
msgstr "Добавление ВМ в пул {} закончилось с ошибками."

#: ../common/models/pool.py:1054
msgid "Required: {}, created: {}."
msgstr "Необходимо: {}, создано: {}."

#: ../common/models/task.py:83
msgid "Creation of pool {}."
msgstr "Создание пула {}."

#: ../common/models/task.py:85
msgid "Expanding of pool {}."
msgstr "Расширение пула {}."

#: ../common/models/task.py:87
msgid "Deleting of pool {}."
msgstr "Удаление пула {}."

#: ../common/models/task.py:89
msgid "Decreasing of pool {}."
msgstr "Уменьшение пула {}."

#: ../common/models/task.py:91
msgid "Preparation of vm {}."
msgstr "Подготовка ВМ {}."

#: ../common/models/task.py:118
msgid "  Duration: {}."
msgstr "  Продолжительность: {}."

#: ../common/models/vm.py:111
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: ../common/models/vm.py:128 ../web_app/thin_client_api/handlers.py:259
#: ../web_app/thin_client_api/handlers.py:286
msgid "VM has no api client."
msgstr "ВМ не имеет клиента. Проверьте состояние контроллера."

#: ../common/models/vm.py:139
msgid "VM deletion task {} finished with error."
msgstr "Задача {} удаления ВМ завершилась с ошибкой."

#: ../common/models/vm.py:140
msgid "VM {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: ../common/models/vm.py:146
msgid "VM {} deletion task finished with error."
msgstr "Задача удаления ВМ {} завершилась с ошибкой."

#: ../common/models/vm.py:163
msgid "User {} has been included to VM {}."
msgstr "ВМ {} закреплена за пользователем {}."

#: ../common/models/vm.py:174
msgid "VM {} is clear from users."
msgstr "ВМ {} освобождена от пользователей."

#: ../common/models/vm.py:211 ../common/models/vm.py:346
msgid "There is no client for controller {}."
msgstr "Контролер {} не имеет подключения к ECP VeiL."

#: ../common/models/vm.py:234
msgid "ECP VeiL controller {} error."
msgstr "Ошибка контроллера ECP VeiL {}."

#: ../common/models/vm.py:241
msgid "Controller has not free space for creating new VM."
msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#: ../common/models/vm.py:242
msgid "Not enough free space on data pool."
msgstr "Недостаточно свободного места в пуле данных."

#: ../common/models/vm.py:245
msgid "Unknown node {}."
msgstr "Неизвестный узел {}."

#: ../common/models/vm.py:246
msgid "Controller can`t create VM. Unknown node."
msgstr "Контроллер не может создать ВМ. Неизвестный узел."

#: ../common/models/vm.py:251
msgid "Possibly blocked by active task on ECP. Wait before next try."
msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."

#: ../common/models/vm.py:254
msgid "Something went wrong. Interrupt while."
msgstr "Что-то пошло не так. Прерываем while."

#: ../common/models/vm.py:273
msgid "VM {} has been removed from the pool."
msgstr "ВМ {} удалена из пула."

#: ../common/models/vm.py:281
msgid "VM {} deleting cancelled by timeout."
msgstr "Удаление ВМ {} отменено по таймауту."

#: ../common/models/vm.py:303 ../web_app/journal/schema.py:162
msgid "No such event."
msgstr "Нет такого события."

#: ../common/models/vm.py:366
msgid "VM {} is powered."
msgstr "ВМ {} включена."

#: ../common/models/vm.py:373
msgid "VM {} already shutdown."
msgstr "ВМ {} уже выключена."

#: ../common/models/vm.py:379
msgid "VM {} is force shutdown."
msgstr "ВМ {} принудительно выключена."

#: ../common/models/vm.py:382
msgid "VM {} is shutdown."
msgstr "ВМ {} выключена."

#: ../common/models/vm.py:390 ../common/models/vm.py:413
msgid "VM {} is shutdown. Please power this."
msgstr "ВМ {} выключена. Пожалуйста включите её."

#: ../common/models/vm.py:397
msgid "VM {} was force reboot."
msgstr "ВМ {} принудительно перезагружена."

#: ../common/models/vm.py:400
msgid "VM {} was reboot."
msgstr "ВМ {} перезагружена."

#: ../common/models/vm.py:409
msgid "VM {} is suspended."
msgstr "ВМ {} приостановлена."

#: ../common/models/vm.py:431
msgid "VM {} remote access enabled."
msgstr "Удаленный доступ ВМ {} включен."

#: ../common/models/vm.py:463
msgid "VM {} hostname setting task failed."
msgstr "Ошибка задания hostname ВМ {}."

#: ../common/models/vm.py:466
msgid "VM {} hostname setting success."
msgstr "ВМ {} успешно задан hostname."

#: ../common/models/vm.py:478
msgid "Active directory object has no service username or password. Including skipped."
msgstr "У директории авторизации не указаны имя пользователя и пароль. Пропускаем."

#: ../common/models/vm.py:497
msgid "VM {} active directory group including error."
msgstr "Ошибка ввода ВМ {} в группу AD."

#: ../common/models/vm.py:502
msgid "VM {} AD group including successful."
msgstr "ВМ {} успешно заведена в контейнер/группу AD."

#: ../common/models/vm.py:522
msgid "VM {} failed to receive DHCP ip address ({})."
msgstr "VM {} не удалось получить IP-адрес по DHCP ({})."

#: ../common/models/vm.py:534
msgid "VM {} domain including task failed."
msgstr "Ошибка включения ВМ {} в домен."

#: ../common/models/vm.py:535
msgid "VM {} AD inclusion success."
msgstr "ВМ {} успешно заведена в AD."

#: ../common/models/vm.py:539
msgid "VM {} AD inclusion skipped."
msgstr "Заведение ВМ {} в домен пропущено."

#: ../common/models/vm.py:557
msgid "VM {} has been prepared."
msgstr "ВМ {} подготовлена."

#: ../common/models/vm.py:566
msgid "{} preparation cancelled by timeout."
msgstr "подготовка {} отменена по таймауту."

#: ../common/models/vm.py:573
msgid "VM {} preparation error."
msgstr "Ошибка подготовки ВМ {}."

#: ../common/veil/auth/veil_jwt.py:26
msgid "Token invalid."
msgstr "Недействительный токен."

#: ../common/veil/auth/veil_jwt.py:31
msgid "Token expired."
msgstr "Срок действия токена истек."

#: ../common/veil/auth/veil_jwt.py:84
msgid "Error with JWT decode."
msgstr "Ошибка JWT декодирования."

#: ../common/veil/auth/veil_jwt.py:94 ../common/veil/auth/veil_jwt.py:96
#: ../common/veil/auth/veil_jwt.py:98
msgid "Invalid authorization header."
msgstr "Неправильный заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:102
msgid "Missing authorization header."
msgstr "Пропущен заголовок авторизации."

#: ../common/veil/veil_decorators.py:44 ../common/veil/veil_decorators.py:47
#: ../web_app/auth/license/handlers.py:38 ../web_app/tests/test_auth_v2.py:75
msgid "Invalid permissions."
msgstr "Недостаточно прав."

#: ../common/veil/veil_decorators.py:45
msgid "IP: {}. username: {}."
msgstr "IP: {}. Пользователь: {}."

#: ../common/veil/veil_errors.py:179
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: ../common/veil/veil_errors.py:186
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: ../common/veil/veil_errors.py:193
msgid "Critical controller error."
msgstr "Критическая ошибка контроллера."

#: ../common/veil/veil_gino.py:84
msgid "Incorrect sort parameter {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/veil/veil_gino.py:94
msgid "Incorrect request parameter {}."
msgstr "Неверный параметр запроса {}."

#: ../common/veil/veil_gino.py:200
msgid "{} {} has been disabled."
msgstr "{} {} деактивирована."

#: ../common/veil/veil_gino.py:201
msgid "{} {} has`t been found in VeiL. Switched to FAILED."
msgstr "{} {} не найдена на VeiL. Переключена в стутус FAILED."

#: ../common/veil/veil_gino.py:210
msgid "Soft_delete exception: {}."
msgstr "Ошибка удаления: {}."

#: ../common/veil/veil_handlers.py:76 ../web_app/thin_client_api/handlers.py:69
#: ../web_app/thin_client_api/handlers.py:95
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: ../common/veil/veil_handlers.py:80
msgid "There is no pool with id: {}."
msgstr "Отсутствует пул с ID: {}."

#: ../common/veil/veil_handlers.py:83
msgid "User {} has no VM on pool {}."
msgstr "У пользователя {} нет виртуальной машины в пуле {}."

#: ../common/veil/veil_redis.py:163
msgid "Redis waiting exception."
msgstr "Ошибка Redis."

#: ../common/veil/veil_redis.py:214
msgid "Redis task waiting exception."
msgstr "Ошибка redis-задачи."

#: ../common/veil/veil_validators.py:32
msgid "Field \"{}\" - {}."
msgstr "Поле \"{}\" - {}."

#: ../pool_worker/pool_tasks.py:79
msgid "Task <{}> started."
msgstr "Задача <{}> начала выполнение."

#: ../pool_worker/pool_tasks.py:87
msgid "Task <{}> finished successfully."
msgstr "Задача <{}> завершилась успешно."

#: ../pool_worker/pool_tasks.py:91
msgid "Task <{}> cancelled."
msgstr "Задача <{}> отменена."

#: ../pool_worker/pool_tasks.py:96
msgid "Exception during task execution. Task: <{}>."
msgstr "Задача <{}> завершилась с ошибками."

#: ../pool_worker/pool_tasks.py:158
msgid "Pool Creation cancelled."
msgstr "Создание пула отменено."

#: ../pool_worker/pool_tasks.py:162
msgid "Failed to init pool."
msgstr "Ошибка инициализации пула."

#: ../pool_worker/pool_tasks.py:175
msgid "Pool initialization VM(s) preparation error."
msgstr "В момент инициализации пула подготовка виртуальных машин завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:232
msgid "VM creating error."
msgstr "Ошибка создания ВМ."

#: ../pool_worker/pool_tasks.py:246
msgid "VM preparation error."
msgstr "Ошибка подготовки ВМ."

#: ../pool_worker/pool_tasks.py:335
msgid "Another task works on this VM."
msgstr "ВМ заблокирована выполнением другой задачи."

#: ../pool_worker/pool_tasks.py:375
msgid "VeiL domain request error."
msgstr "Ошибка запроса VeiL ВМ."

#: ../pool_worker/pool_tasks.py:378
msgid "Task has`t been created."
msgstr "Задача не была создана."

#: ../pool_worker/pool_tasks.py:392
msgid "VM remote access task {} finished with error."
msgstr "Задава {} включения удаленного доступа ВМ завершилась с ошибкой."

#: ../web_app/app.py:84
msgid "VDI broker stopped."
msgstr "VDI брокер остановлен."

#: ../web_app/app.py:94
msgid "VDI broker started with {} worker(s)."
msgstr "VDI брокер запущен в {} экземпляре(ах)."

#: ../web_app/app.py:97
msgid "Authentication system is disabled."
msgstr "Система аутентификации выключена."

#: ../web_app/app.py:100
msgid "The license is expired. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла. Некоторые функции будут заблокированы. Свяжитесь с вашим поставщиком."

#: ../web_app/app.py:102
msgid "DEBUG mode is enabled."
msgstr "Режим отладки включен."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:33
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:211
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:261
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:423
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:441
msgid "No such Authentication Directory."
msgstr "Такая Authentication Directory отсутствует."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:39
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на директорию авторизации должна начинаться с ldap(s)://."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:46
msgid "Verbose name should not be empty."
msgstr "Имя verbose не должно быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:52
msgid "Value should be 1-63 latin characters, -, . or _."
msgstr "Значение должно быть в диапазоне от 1-63 латинских символа, -, . или _."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:68
#: ../web_app/auth/group_schema.py:45
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:70
msgid "groups list is empty."
msgstr "Список групп пуст."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:77
msgid "No such mapping."
msgstr "Нет такого отображения."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:83
msgid "DC should not be empty."
msgstr "Класс объекта домена не должен быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:207
msgid "Specify id."
msgstr "Укажите ID."

#: ../web_app/auth/group_schema.py:27 ../web_app/auth/group_schema.py:108
msgid "No such group."
msgstr "Отсутствует такая группа."

#: ../web_app/auth/group_schema.py:35
msgid "verbose name must me <= 128 characters."
msgstr "имя должно быть <= 128 символов."

#: ../web_app/auth/group_schema.py:36
msgid "verbose_name is empty."
msgstr "имя пустое."

#: ../web_app/auth/group_schema.py:47
msgid "users list is empty."
msgstr "список пользователей пуст."

#: ../web_app/auth/group_schema.py:52
msgid "Last name length must be <= 255 characters."
msgstr "Фамилия должна быть <= 255 символам."

#: ../web_app/auth/group_schema.py:174
msgid "Specify Group.id or Group.ad_guid."
msgstr "Укажите Group.id или Group.ad_guid."

#: ../web_app/auth/group_schema.py:176
msgid "Specify Group.id or Group.ad_guid. Not both."
msgstr "Укажите Group.id или Group.ad_guid. Не оба."

#: ../web_app/auth/handlers.py:23
msgid "Missing request body."
msgstr "Отсутствует тело запроса."

#: ../web_app/auth/handlers.py:25
msgid "Missing username and password."
msgstr "Отсутствует имя пользователя и пароль."

#: ../web_app/auth/handlers.py:30
msgid "Missing username."
msgstr "Отсутствует имя пользователя."

#: ../web_app/auth/handlers.py:32
msgid "Missing password."
msgstr "Отсутствует пароль."

#: ../web_app/auth/handlers.py:39
msgid "External auth system is disabled. Check broker settings."
msgstr "Внешняя служба авторизации отключена. Проверьте настройки брокера."

#: ../web_app/auth/handlers.py:45
msgid "Invalid credentials."
msgstr "Неверные учетные данные."

#: ../web_app/auth/handlers.py:47
msgid "Local auth system is disabled. Check broker settings."
msgstr "Локальная служба авторизации отключена. Проверьте настройки брокера."

#: ../web_app/auth/handlers.py:56
msgid "Authentication failed for user: {}."
msgstr "Ошибка авторизации пользователя: {}."

#: ../web_app/auth/handlers.py:68
msgid "User {} logged out."
msgstr "Пользователь {} вышел из системы."

#: ../web_app/auth/handlers.py:78
msgid "Demo version."
msgstr "Демонстрационная версия."

#: ../web_app/auth/license/handlers.py:53
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: ../web_app/auth/license/handlers.py:61
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: ../web_app/auth/license/handlers.py:63
msgid "Try to upload invalid license key."
msgstr "Неудачная попытка загрузить лицензионный ключ."

#: ../web_app/auth/license/handlers.py:66
msgid "Valid license key is uploaded."
msgstr "Лицензионный ключ загружен."

#: ../web_app/auth/user_schema.py:26 ../web_app/auth/user_schema.py:180
msgid "No such user."
msgstr "Нет такого пользователя."

#: ../web_app/auth/user_schema.py:36
msgid "username must contain >= 3 chars (letters, digits, _, -, +) and can't contain any spaces."
msgstr "имя пользователя должно быть >= 3 символов (буквы, цифры, _, -, +) и не содержать пробелов."

#: ../web_app/auth/user_schema.py:43
msgid "Email {} is already busy."
msgstr "Email {} занят."

#: ../web_app/auth/user_schema.py:51
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: ../web_app/auth/user_schema.py:66
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: ../web_app/auth/user_schema.py:72
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: ../web_app/auth/user_schema.py:176
msgid "Specify id or username."
msgstr "Укажите ID или имя пользователя."

#: ../web_app/controller/resource_schema.py:350
#: ../web_app/thin_client_api/handlers.py:145
msgid "VM is unreachable on ECP Veil."
msgstr "ВМ недоступна на ECP Veil."

#: ../web_app/controller/schema.py:28
msgid "name can`t be empty."
msgstr "имя не может быть пустым."

#: ../web_app/controller/schema.py:34
msgid "name `{}` is busy."
msgstr "имя `{}` уже используется."

#: ../web_app/controller/schema.py:42
msgid "address can`t be empty."
msgstr "адресс не может быть пустым."

#: ../web_app/controller/schema.py:48
msgid "address `{}` is busy."
msgstr "адресс `{}` уже используется."

#: ../web_app/controller/schema.py:55
msgid "token can`t be empty."
msgstr "токен не может быть пустым."

#: ../web_app/controller/schema.py:67 ../web_app/pool/schema.py:50
msgid "No such controller."
msgstr "Нет такого контроллера."

#: ../web_app/controller/schema.py:314 ../web_app/controller/schema.py:345
msgid "Connection to ECP has been failed."
msgstr "Соединение с ECP не удалось."

#: ../web_app/front_ws_api/handlers.py:40
msgid "WebSocket opened."
msgstr "WebSocket открыт."

#: ../web_app/front_ws_api/handlers.py:45
msgid "Message: {}."
msgstr "Сообщение: {}."

#: ../web_app/front_ws_api/handlers.py:58
msgid "WS listener error."
msgstr "Ошибка сервиса прослушивания WS."

#: ../web_app/front_ws_api/handlers.py:59
msgid "Unknown subscription source."
msgstr "Неизвестный источник подписки."

#: ../web_app/front_ws_api/handlers.py:71
msgid "Already subscribed."
msgstr "Уже подписан."

#: ../web_app/front_ws_api/handlers.py:75
msgid "Not subscribed."
msgstr "Не подписан."

#: ../web_app/front_ws_api/handlers.py:120
#: ../web_app/thin_client_api/handlers.py:467
msgid "Write error."
msgstr "Ошибка записи."

#: ../web_app/journal/schema.py:148
msgid "The sort parameter is incorrect."
msgstr "Неверный параметр сортировки."

#: ../web_app/journal/schema.py:223
msgid "Journal is exported."
msgstr "Журнал экспортирован."

#: ../web_app/pool/schema.py:123 ../web_app/pool/schema.py:450
#: ../web_app/pool/schema.py:471
msgid "No such pool."
msgstr "Нет такого пула."

#: ../web_app/pool/schema.py:133
msgid "Pool name must contain only characters, digits, _, -."
msgstr "Имя пула должно содержать только буквы, цифры, _, -."

#: ../web_app/pool/schema.py:146
msgid "Template name of VM must contain only characters, digits, -. Template name length must be in [{} {}] interval."
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, -. Длина шаблонного имени должна быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:155
msgid "Initial number of VM must be in {}-{} interval."
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:171
msgid "Reserve size of VMs can not be more than maximal number of Vms."
msgstr "Резервное число ВМ не может быть больше максимального числа ВМ."

#: ../web_app/pool/schema.py:174
msgid "Reserve size of VM must be in {}-{} interval."
msgstr "Резервное число ВМ должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:195
msgid "Maximal number of created VM can not be less than initial number of VM."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ."

#: ../web_app/pool/schema.py:197
msgid "Maximal number of created VM must be in [{} {}] interval."
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:200
msgid "Maximal number of created VMs can not be less than current amount of Vms."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше текущего числа ВМ."

#: ../web_app/pool/schema.py:215
msgid "Increase step must be positive and less or equal to total_size."
msgstr "Шаг увеличения должен быть положительным и меньше или равен общему количеству."

#: ../web_app/pool/schema.py:221
msgid "Connection type cannot be empty."
msgstr "Тип подключения не может быть пустым."

#: ../web_app/pool/schema.py:541
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: ../web_app/pool/schema.py:572
msgid "VM {} is already in one of pools."
msgstr "Виртуальная машина {} уже в одном из пулов."

#: ../web_app/pool/schema.py:585
msgid "VM {} has been added to the pool {}."
msgstr "ВМ {} добавлена в пул {}."

#: ../web_app/pool/schema.py:605 ../web_app/pool/schema.py:832
msgid "List of VM should not be empty."
msgstr "Список виртуальных машин не должен быть пустым."

#: ../web_app/pool/schema.py:615 ../web_app/pool/schema.py:842
msgid "VM doesn't belong to specified pool."
msgstr "Виртуальная машина не принадлежит заданному пулу."

#: ../web_app/pool/schema.py:643
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:669
msgid "Can not expand pool {} because it reached its total_size."
msgstr "Не удается расширить пул {} т.к. достигнут максимальный размер."

#: ../web_app/pool/schema.py:674
msgid "Another task works on pool {}."
msgstr "Другая задача выполняется над пулом {}."

#: ../web_app/pool/schema.py:679
msgid "Increase_step {}."
msgstr "Шаг расширения пула {}."

#: ../web_app/pool/schema.py:680
msgid "Expansion of pool {} requested."
msgstr "Запрошено расширение пула {}."

#: ../web_app/pool/schema.py:743
msgid "Failed to create automated pool {}."
msgstr "Ошибка создания автоматического пула {}."

#: ../web_app/pool/schema.py:813
msgid "Failed to update automated pool {}. Name must be unique."
msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:952
msgid "There is no VM {}."
msgstr "Нет ВМ {}."

#: ../web_app/pool/schema.py:969
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: ../web_app/pool/schema.py:1010
msgid "Another task works on VM {}."
msgstr "Другая задача выполняется над ВМ {}."

#: ../web_app/pool/schema.py:1112
msgid "Only VM with Windows OS can be in domain."
msgstr "Только ВМ на ОС Windows могут находиться в домене."

#: ../web_app/task/schema.py:82
msgid "No such task."
msgstr "Нет такого задания."

#: ../web_app/task/schema.py:102
msgid "No such task or status of task {} is not {}."
msgstr "Нет такого задания или статус задания {} не {}."

#: ../web_app/thin_client_api/handlers.py:73
msgid "User {} requested pools data."
msgstr "Пользователь {} запросил список пулов."

#: ../web_app/thin_client_api/handlers.py:90
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: ../web_app/thin_client_api/handlers.py:99
msgid "Pool not found."
msgstr "Пул не найден."

#: ../web_app/thin_client_api/handlers.py:105
msgid "The pool doesnt support connection type {}."
msgstr "Пул не поддерживает тип соединения {}."

#: ../web_app/thin_client_api/handlers.py:124
msgid "The pool doesn`t have free machines. Try again after 5 minutes."
msgstr "В пуле нет свободных машин. Повторите попытку через 5 минут."

#: ../web_app/thin_client_api/handlers.py:129
msgid "The pool doesn`t have free machines."
msgstr "В пуле нет свободных машин."

#: ../web_app/thin_client_api/handlers.py:151
msgid "User {} connected to pool {}."
msgstr "Пользователь {} подключился к пулу {}."

#: ../web_app/thin_client_api/handlers.py:153
msgid "User {} connected to VM {}."
msgstr "Пользователь {} подключился к ВМ {}."

#: ../web_app/thin_client_api/handlers.py:162
msgid "The remote controller is unavailable."
msgstr "Контроллер недоступен."

#: ../web_app/thin_client_api/handlers.py:174
msgid "VM does not support RDP. The controller didn`t provide a VM address."
msgstr "Виртуальная машина не поддерживает RDP. Контроллер не передал адрес ВМ."

#: ../web_app/thin_client_api/handlers.py:234
msgid "User {} executed action {} on VM {}."
msgstr "Пользователь {} выполнил действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:236
msgid "User {} failed to execute action {} on VM {}."
msgstr "Пользователю {} не удалось выполнить действие {} над ВМ {}."

#: ../ws_listener_worker/resources_monitor.py:106
msgid "{} is connected: {}."
msgstr "{} подключен: {}."

#: ../ws_listener_worker/resources_monitor.py:151
msgid "Resource monitor can`t connect to controller."
msgstr "Не удается подключиться к контроллеру."

#: ../ws_listener_worker/resources_monitor.py:152
msgid "Can`t connect to {}."
msgstr "Не удается подключиться к {}."

#: ../ws_listener_worker/resources_monitor.py:173
msgid "Closing ws connection {}."
msgstr "Закрываем WS соединение {}."

#: ../ws_listener_worker/resources_monitor_manager.py:63
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}."
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: ../ws_listener_worker/resources_monitor_manager.py:73
msgid "{}: Started."
msgstr "{}: Запущен."

#: ../ws_listener_worker/resources_monitor_manager.py:88
#, python-brace-format
msgid "{cls}: Controller {name} is already monitored."
msgstr "{cls}: Контроллер {name} уже отслеживается."

#: ../ws_listener_worker/resources_monitor_manager.py:95
#, python-brace-format
msgid "{cls}: resource monitor for controller {name} connected."
msgstr "{cls}: монитор ресурсов для контроллера {name} подключен."

#~ msgid "Roles: {} was deleted to pool {}."
#~ msgstr "Роли: {} удалены в пуле {}."

#~ msgid "Pool already has role."
#~ msgstr "Пул уже имеет роль."

#~ msgid "Role {} has been set to pool {}."
#~ msgstr "Роль {} добавлена в пул {}."
