# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <emil@emil-pc>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-07 15:59+0300\n"
"PO-Revision-Date: 2020-07-30 11:25+0300\n"
"Last-Translator: Emil <emil@emil-pc>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../common/log/journal.py:192 ../common/log/journal.py:310
msgid "INFO message from VeiL Broker."
msgstr "Информационное сообщение с VeiL VDI брокера."

#: ../common/log/journal.py:209
msgid "Warning message from VeiL Broker."
msgstr "Сообщение о предупреждении на VeiL VDI брокера."

#: ../common/log/journal.py:226
msgid "Error message from VeiL Broker."
msgstr "Сообщение об ошибке на VeiL VDI брокера."

#: ../common/log/journal.py:259
msgid "SMTP server is not configured."
msgstr "SMTP сервер не настроен."

#: ../common/log/journal.py:302
msgid "Error in smtp server: {}."
msgstr "Ошибка связанная с SMTP сервером: {}."

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:84
msgid "Add new journal archive."
msgstr "Добавлен новый архив журнала."

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:85
msgid "Archive name:"
msgstr "Имя архива:"

#: ../common/migrations/versions/70220709e7b7_journal_and_settings.py:86
msgid "path:"
msgstr "путь:"

#: ../common/models/active_tk_connection.py:167
msgid "User {} connected to VM {}."
msgstr "Пользователь {} подключился к ВМ {}."

#: ../common/models/active_tk_connection.py:176
msgid "User {} disconnected from VM {}."
msgstr "Пользователь {} отключился от ВМ {}."

#: ../common/models/active_tk_connection.py:199
msgid "User {} failed to connect to VM {}."
msgstr "Пользователю {} не удалось подключиться к ВМ {}."

#: ../common/models/active_tk_connection.py:201
msgid "Error code: {}. Error message: {}."
msgstr "Код ошибки: {}. Сообщение об ошибке: {}."

#: ../common/models/auth.py:244 ../common/models/auth.py:668
#: ../web_app/auth/user_schema.py:38
msgid "username can`t be empty."
msgstr "имя пользователя не может быть пустым."

#: ../common/models/auth.py:249 ../web_app/auth/user_schema.py:44
msgid "username must be <= 128 characters."
msgstr "имя пользователя должно быть <= 128 символов."

#: ../common/models/auth.py:256
msgid "username {} must contain letters, digits, _, +, begin from letter and can't contain any spaces."
msgstr "имя пользователя {} должно состоять из букв, цифр, _, +, начинаться с буквы и не содержать пробелов."

#: ../common/models/auth.py:287
msgid "Role {} is added to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:295 ../common/models/auth.py:323
msgid "User {} roles: {}."
msgstr "Роли пользователя {}: {}."

#: ../common/models/auth.py:300
msgid "Role {} is assigned to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:312
msgid "Roles: {} was deleted to user {}."
msgstr "Роли: {} удалены у пользователя {}."

#: ../common/models/auth.py:371
msgid "User {} already has permission {}."
msgstr "Пользователь {} уже имеет разрешение."

#: ../common/models/auth.py:379
msgid "Permission(s) {} added to user {}."
msgstr "Разрешения {} назначены пользователю {}."

#: ../common/models/auth.py:402
msgid "Permission(s) {} removed from user {}."
msgstr "Разрешения {} удалены у пользователя {}."

#: ../common/models/auth.py:411
msgid "User {} permission(s): {}."
msgstr "Разрешения пользователя {}: {}."

#: ../common/models/auth.py:425
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: ../common/models/auth.py:436
#, python-brace-format
msgid "User {username} has been activated on Astra."
msgstr "Пользователь {username} был активирован в системе."

#: ../common/models/auth.py:457
msgid "There is no more active superuser."
msgstr "Больше нет активного администратора."

#: ../common/models/auth.py:466
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: ../common/models/auth.py:488
#, python-brace-format
msgid "User {username} has been deactivated on Astra."
msgstr "Пользователь {username} деактивирован в системе."

#: ../common/models/auth.py:533
msgid "Invalid credentials. Check or create password for user {}."
msgstr "Неверные учетные данные. Проверьте или создайте пароль для пользователя {}."

#: ../common/models/auth.py:543 ../common/models/auth.py:591
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: ../common/models/auth.py:549
#, python-brace-format
msgid "Password of user {username} has`t been changed."
msgstr "Пароль пользователя {username} не был изменен."

#: ../common/models/auth.py:588
msgid "Password of user {} has been changed to the local password."
msgstr "Пароль пользователя {} изменен на локальный пароль."

#: ../common/models/auth.py:643
#, python-brace-format
msgid "Local user {username} was converted to domain user."
msgstr "Локальный пользователь {username} был преобразован в доменного пользователя."

#: ../common/models/auth.py:691
msgid "Superuser."
msgstr "Администратор."

#: ../common/models/auth.py:691 ../common/models/auth.py:706
#: ../common/models/auth.py:718
msgid "User."
msgstr "Пользователь."

#: ../common/models/auth.py:708
msgid "You must change password for user {}. Check a reason in description."
msgstr "Необходимо изменить пароль для пользователя {}. Причина в описании."

#: ../common/models/auth.py:722
msgid "User {} was created in Astra Linux before. Please try to create him with correct password or delete in Astra Linux before trying to create in VeiL VDI again."
msgstr "Пользователь {} был ранее создан в Astra Linux. Пожалуйста, попробуйте создать его с правильным паролем или удалите его в Astra Linux, прежде чем снова пытаться создать в VeiL VDI."

#: ../common/models/auth.py:726
msgid "User {} was created in Astra Linux before. Please delete him there before trying to create in Broker again."
msgstr "Пользователь {} был ранее создан в Astra Linux. Пожалуйста удалите его оттуда, прежде чем снова пересоздать в Брокере."

#: ../common/models/auth.py:736
msgid "User {} creation error."
msgstr "Ошибка создания пользователя {}."

#: ../common/models/auth.py:747
msgid "Your password is incorrect for user {}. Check description in journal."
msgstr "Пароль неверен для пользователя {}. Проверьте описание в журнале."

#: ../common/models/auth.py:758
msgid "{} {} created."
msgstr "{} {} создан."

#: ../common/models/auth.py:817
msgid "User {} update error."
msgstr "Ошибка обновления пользователя {}."

#: ../common/models/auth.py:829
msgid "Values of user {} is changed."
msgstr "Параметры пользователя {} изменены."

#: ../common/models/auth.py:836 ../common/models/auth.py:847
msgid "Roles: {}."
msgstr "Роли: {}."

#: ../common/models/auth.py:837
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал администратором."

#: ../common/models/auth.py:848
#, python-brace-format
msgid "User {username} is no longer a superuser."
msgstr "Пользователь {username} перестал быть администратором."

#: ../common/models/auth.py:879
#, python-brace-format
msgid "User {username} has been logged in."
msgstr "Пользователь {username} вошел в систему."

#: ../common/models/auth.py:882
msgid "Auth type: {}, IP: {}, Client type: {}."
msgstr "Тип авторизации: {}, IP: {}, тип клиента: {}."

#: ../common/models/auth.py:905
#, python-brace-format
msgid "User {username} has been logged out."
msgstr "Пользователь {username} вышел из системы."

#: ../common/models/auth.py:922
msgid "QR code and secret code of 2fa were repeated for user {}."
msgstr "QR код и секретный код для двухфакторной аутентификации были повторены для пользователя {}."

#: ../common/models/auth.py:926
msgid "New QR code and secret code of 2fa were generated for user {}."
msgstr "Новый QR код и секретный код для двухфакторной аутентификации были созданы для пользователя {}."

#: ../common/models/auth.py:941
msgid "One-time password does not match or is out of date."
msgstr "Одноразовый пароль не совпадает или устарел."

#: ../common/models/auth.py:1071
msgid "Group {} is created."
msgstr "Группа {} создана."

#: ../common/models/auth.py:1105
msgid "Group {} already has permission {}."
msgstr "Группа {} уже имеет разрешение {}."

#: ../common/models/auth.py:1113
msgid "Permission(s) {} added to group {}."
msgstr "Разрешения: {} добавлены группе {}."

#: ../common/models/auth.py:1136
msgid "Permission(s) {} removed from group {}."
msgstr "Разрешения {} удалены у группы {}."

#: ../common/models/auth.py:1145
msgid "Group {} permission(s): {}."
msgstr "Разрешения группы {}: {}."

#: ../common/models/auth.py:1163
msgid "Values of group {} is updated."
msgstr "Параметры группы {} обновлены."

#: ../common/models/auth.py:1186
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: ../common/models/auth.py:1193
msgid "User {} is already in group {}."
msgstr "Пользователь {} уже находится в группе {}."

#: ../common/models/auth.py:1205
msgid "Removing user {} from group {}."
msgstr "Удаление пользователя {} из группы {}."

#: ../common/models/auth.py:1218
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: ../common/models/auth.py:1225
msgid "Group {} has already role {}."
msgstr "Группе {} уже назначена роль {}."

#: ../common/models/auth.py:1238
msgid "Roles: {} was deleted to group {}."
msgstr "Роли: {} удалены из группы {}."

#: ../common/models/authentication_directory.py:192
#: ../web_app/tests/test_auth_dir.py:177
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной службы каталогов."

#: ../common/models/authentication_directory.py:216
msgid "Authentication directory {} is created."
msgstr "Служба каталогов {} создана."

#: ../common/models/authentication_directory.py:251
msgid "Values for auth directory is updated."
msgstr "Значения службы каталогов обновлены."

#: ../common/models/authentication_directory.py:286
msgid "Arguments: {} of group: {}."
msgstr "Аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:289
msgid "Mapping for auth directory {} is created."
msgstr "Сопоставление для службы каталогов {} создано."

#: ../common/models/authentication_directory.py:325
msgid "New arguments: {} of group: {}."
msgstr "Новые аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:328
msgid "Mapping for auth directory {} is updated."
msgstr "Сопоставление для службы каталогов {} обновлено."

#: ../common/models/authentication_directory.py:358
#: ../common/models/authentication_directory.py:719
msgid "Failed to connect to authentication directory server {}."
msgstr "Не удалось подключиться к серверу службы каталогов LDAP {}."

#: ../common/models/authentication_directory.py:368
msgid "Authentication directory server {} is connected."
msgstr "Сервер службы каталогов {} подключен."

#: ../common/models/authentication_directory.py:451
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: ../common/models/authentication_directory.py:467
msgid "Username {} is incorrect. Maybe you mean {}."
msgstr "Имя пользователя {} неверное. Может быть вы имели в виду {}."

#: ../common/models/authentication_directory.py:470
#, python-brace-format
msgid "Username {username} is incorrect."
msgstr "Имя пользователя {username} неверное."

#: ../common/models/authentication_directory.py:473
msgid "User {} is deactivate."
msgstr "Пользователь {} деактивирован."

#: ../common/models/authentication_directory.py:503
msgid "Mappings: {}."
msgstr "Сопоставления: {}."

#: ../common/models/authentication_directory.py:527
msgid "escaped values: {}."
msgstr "скрытые значения: {}."

#: ../common/models/authentication_directory.py:529
msgid "role mapping value type: {}."
msgstr "тип значений отображения роли: {}."

#: ../common/models/authentication_directory.py:542
msgid "User VeiL groups: {}."
msgstr "Группы пользователей VeiL: {}."

#: ../common/models/authentication_directory.py:550
msgid "Attaching user {} to group: {}."
msgstr "Прикрепление пользователя {} к группе {}."

#: ../common/models/authentication_directory.py:571
#: ../common/models/authentication_directory.py:613
msgid "No authentication directory controllers."
msgstr "Нет контроллеров служб каталогов."

#: ../common/models/authentication_directory.py:586
#: ../web_app/auth/handlers.py:55
msgid "Invalid credentials."
msgstr "Неверные учетные данные."

#: ../common/models/authentication_directory.py:604
msgid "LDAP auth timeout."
msgstr "Тайм-аут аутентификации LDAP"

#: ../common/models/authentication_directory.py:642
msgid "Invalid credentials (ldap): {}."
msgstr "Неверные учетные данные (ldap): {}."

#: ../common/models/authentication_directory.py:647
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: ../common/models/authentication_directory.py:651
msgid "The LDAP server provides an alternate address to which an LDAP request can be processed, but the attempt was unsuccessful."
msgstr "Сервер LDAP предоставляет альтернативный адрес, по которому может быть обработан запрос LDAP, но попытка было неудачной."

#: ../common/models/authentication_directory.py:662
msgid "Invalid credentials (ldap Referral): {}."
msgstr "Неверные учетные данные (ldap Referral): {}."

#: ../common/models/authentication_directory.py:665
msgid "Referral server is down (ldap)."
msgstr "Referral сервер не отвечает (ldap)."

#: ../common/models/authentication_directory.py:703
msgid "LDAP username and password can`t be empty."
msgstr "Имя пользователя и пароль LDAP не могут быть пустыми."

#: ../common/models/authentication_directory.py:712
msgid "Authentication directory server {} has bad auth info."
msgstr "Не удалось подключиться к серверу службы каталогов {}."

#: ../common/models/authentication_directory.py:851
#: ../common/models/authentication_directory.py:1101
msgid "Fail to connect to Authentication Directory. Check service information."
msgstr "Ошибка подключения к службе каталогов."

#: ../common/models/authentication_directory.py:1077
msgid "{} new users synced from Authentication Directory."
msgstr "{} новых пользователей синхронизировано из службы каталогов."

#: ../common/models/authentication_directory.py:1089
#: ../web_app/auth/group_schema.py:251
msgid "No such Group."
msgstr "Отсутствует такая группа."

#: ../common/models/authentication_directory.py:1093
msgid "Group {} is not synchronized by AD."
msgstr "Группа {} не синхронизирована со службой каталогов."

#: ../common/models/authentication_directory.py:1109
msgid "There is no users to sync in group {group.verbose_name}."
msgstr "В группе {group.verbose_name} не найдены пользователи для синхронизации."

#: ../common/models/controller.py:143
msgid "Controller {} has no api client."
msgstr "Контроллер {} не имеет подключения к ECP VeiL."

#: ../common/models/controller.py:149
msgid "ECP VeiL version could not be obtained. Check your token."
msgstr "Не удается получить версию ECP VeiL. Проверьте свой токен."

#: ../common/models/controller.py:157
msgid "ECP VeiL version should be 4.3 or higher. Current version is incompatible."
msgstr "Версия ECP VeiL должна быть 4.3 или выше. Текущая версия не поддерживается."

#: ../common/models/controller.py:189
msgid "Controller {} added."
msgstr "Контроллер {} добавлен."

#: ../common/models/controller.py:245
msgid "Controller {} has been successfully updated."
msgstr "Контроллер {} успешно обновлен."

#: ../common/models/controller.py:249
msgid "Controller {} update failed."
msgstr "Ошибка обновления контроллера {}."

#: ../common/models/controller.py:278
msgid "Controller {} has been removed."
msgstr "Контроллер {} удалён."

#: ../common/models/controller.py:309
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: ../common/models/controller.py:332 ../common/models/controller.py:359
msgid "Controller {} status has been switched to {}."
msgstr "Статус контроллера {} изменен на {}."

#: ../common/models/controller.py:377
msgid "No such controller."
msgstr "Нет такого контроллера."

#: ../common/models/event.py:74
msgid "Journal in this period is empty."
msgstr "Журнал для этого периода пуст."

#: ../common/models/event.py:91
msgid "Path {} is incorrect."
msgstr "Неверный путь: {}."

#: ../common/models/event.py:94
msgid "Check date. Interval {} - {} is incorrect."
msgstr "Проверьте дату. Некорректный промежуток {} - {}."

#: ../common/models/event.py:99
msgid "Not enough free space."
msgstr "Недостаточно свободного места."

#: ../common/models/event.py:101
msgid "Journal export error."
msgstr "Ошибка экспорта журнала."

#: ../common/models/event.py:240
msgid "Choose right period."
msgstr "Выберите правильный период."

#: ../common/models/event.py:246
msgid "Count must be more than 1."
msgstr "Количество должно быть больше 1."

#: ../common/models/event.py:250
msgid "Journal settings changed."
msgstr "Настройки журнала изменены."

#: ../common/models/license.py:75
msgid "Valid license key is uploaded."
msgstr "Лицензионный ключ загружен."

#: ../common/models/license.py:82
msgid "OS error."
msgstr "Системная ошибка."

#: ../common/models/license.py:84
msgid "Wrong Licence file format."
msgstr "Неверный формат файла лицензии."

#: ../common/models/pool.py:225
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/models/pool.py:369 ../common/models/pool.py:1807
msgid "Pool {} has been updated."
msgstr "Пул {} обновлен."

#: ../common/models/pool.py:650
msgid "User {} has been included to pool {}."
msgstr "Пользователь {} был включен в пул {}."

#: ../common/models/pool.py:661 ../common/models/vm.py:334
msgid "{} already has permission."
msgstr "{} уже имеет разрешение."

#: ../common/models/pool.py:684
msgid "Removing user {} from pool {}."
msgstr "Удаление пользователя {} из пула {}."

#: ../common/models/pool.py:692
msgid "User {} has no direct right to pool {}."
msgstr "У пользователя {} нет прямых прав на пул {}. Пропускаем."

#: ../common/models/pool.py:724
msgid "Group {} has been included to pool {}."
msgstr "Группа {} включена в пул {}."

#: ../common/models/pool.py:735
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: ../common/models/pool.py:749
msgid "Removing group {} from pool {}."
msgstr "Удаление группы {} из пула {}."

#: ../common/models/pool.py:800
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: ../common/models/pool.py:836
msgid "Delete VMs for GuestPool {}."
msgstr "Удаление виртуальных машин для гостевого пула {}."

#: ../common/models/pool.py:841
msgid "Delete VMs for AutomatedPool {}."
msgstr "Удаление виртуальных машин для автоматического пула {}."

#: ../common/models/pool.py:848
msgid "VM {} has been removed from ECP VeiL."
msgstr "ВМ {} удалена из ECP VeiL."

#: ../common/models/pool.py:870
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: ../common/models/pool.py:905
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: ../common/models/pool.py:922
msgid "Pool {} status changed to {}."
msgstr "Статус пула {} изменен на {}."

#: ../common/models/pool.py:1106 ../web_app/journal/schema.py:284
msgid "The sort parameter is incorrect."
msgstr "Неверный параметр сортировки."

#: ../common/models/pool.py:1117
msgid "List of VM should not be empty."
msgstr "Список виртуальных машин не должен быть пустым."

#: ../common/models/pool.py:1134
msgid "VM doesn't belong to specified pool."
msgstr "Виртуальная машина не принадлежит заданному пулу."

#: ../common/models/pool.py:1145
msgid "VM {} has been removed from the pool {} and ECP VeiL."
msgstr "ВМ {} удалена из пула {} и из ECP VeiL."

#: ../common/models/pool.py:1149
msgid "VM {} has been removed from the pool {}."
msgstr "ВМ {} удалена из пула {}."

#: ../common/models/pool.py:1218
#, python-brace-format
msgid "Tag {name} created for pool {name}."
msgstr "Тэг {name} добавлен к пулу {name}."

#: ../common/models/pool.py:1238
msgid "Tag {} removed from ECP VeiL."
msgstr "Тэг {} удален из ECP VeiL."

#: ../common/models/pool.py:1250
#, python-brace-format
msgid "Tag {name} updated for pool {name} and all vms in pool."
msgstr "Тэг {name} обновлен для пула {name} и всех ВМ в пуле."

#: ../common/models/pool.py:1277
msgid "Tag {} removed from VM {}."
msgstr "Тэг {} удален для ВМ {}."

#: ../common/models/pool.py:1292 ../common/models/pool.py:1310
msgid "Tag {} added to VM {}."
msgstr "Тэг {} назначен ВМ {}."

#: ../common/models/pool.py:1388
msgid "RDS pool {} created."
msgstr "Пул приложений {} создан."

#: ../common/models/pool.py:1509 ../common/models/pool.py:1512
#: ../common/models/pool.py:1986
msgid "VM {} created."
msgstr "ВМ {} создана."

#: ../common/models/pool.py:1513 ../common/models/pool.py:1988
msgid "VM {} created and added to the pool {}."
msgstr "ВМ {} создана и добавлена в пул {}."

#: ../common/models/pool.py:1524
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: ../common/models/pool.py:1700
msgid "Initial_size: {}, total_size: {}, increase_step {}, reserve_size {}."
msgstr "Начальный размер: {}, Максимальный размер: {}, Шаг расширения: {}, Резервный размер: {}."

#: ../common/models/pool.py:1704
msgid "GuestPool {} is created."
msgstr "Создан гостевой пул {}."

#: ../common/models/pool.py:1711
msgid "AutomatedPool {} is created."
msgstr "Создан автоматический пул {}."

#: ../common/models/pool.py:1764 ../common/models/pool.py:1797
msgid "Update Pool {} values."
msgstr "Обновление значений пула {}."

#: ../common/models/pool.py:1893
msgid "There is no client for pool {}."
msgstr "Пул {} не имеет подключения к ECP VeiL. Проверьте контроллер."

#: ../common/models/pool.py:1932
msgid "VM creation task {} finished with error."
msgstr "Задача {} создания ВМ завершилась с ошибкой."

#: ../common/models/pool.py:1948
msgid "Fail to cancel VM creation task."
msgstr "Ошибка отмены задачи создания ВМ."

#: ../common/models/pool.py:2040
msgid "VM creation error."
msgstr "Ошибка создания ВМ."

#: ../common/models/pool.py:2053
msgid "{} vm(s) are successfully added in the {} pool."
msgstr "{} ВМ успешно добавлены в пул {}."

#: ../common/models/pool.py:2058
msgid "Adding VM to the pool {} finished with errors."
msgstr "Добавление ВМ в пул {} закончилось с ошибками."

#: ../common/models/pool.py:2061
msgid "Required: {}, created: {}."
msgstr "Необходимо: {}, создано: {}."

#: ../common/models/pool.py:2101
msgid "VM preparation error."
msgstr "Ошибка подготовки ВМ."

#: ../common/models/settings.py:41
msgid "Settings changed."
msgstr "Настройки изменены."

#: ../common/models/settings.py:69
msgid "Smtp settings are changed."
msgstr "Настройки SMTP сервера изменены."

#: ../common/models/vm.py:156
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: ../common/models/vm.py:182 ../common/models/vm.py:267
#: ../web_app/thin_client_api/handlers.py:565
#: ../web_app/thin_client_api/handlers.py:595
msgid "VM has no api client."
msgstr "ВМ не имеет клиента. Проверьте состояние контроллера."

#: ../common/models/vm.py:205
msgid "Failed to create multi-delete task."
msgstr "Не удалось создать задачу множественного удаления."

#: ../common/models/vm.py:224 ../common/models/vm.py:287
msgid "VM deletion task {} finished with error."
msgstr "Задача {} удаления ВМ завершилась с ошибкой."

#: ../common/models/vm.py:240
msgid "VM multi-deletion task finished with error. Please see task details on VeiL ECP."
msgstr "Задача множественного удаления ВМ завершена с ошибкой. Пожалуйста посмотрите детали задачи на VeiL ECP."

#: ../common/models/vm.py:241
msgid "VMs: {}."
msgstr "ВМ: {}."

#: ../common/models/vm.py:292
msgid "VM {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: ../common/models/vm.py:299
msgid "VM {} deletion task finished with error."
msgstr "Задача удаления ВМ {} завершилась с ошибкой."

#: ../common/models/vm.py:326
msgid "User {} has been included to VM {}."
msgstr "За пользователем {} закреплена ВМ {}."

#: ../common/models/vm.py:355
msgid "VM {} is clear from {} users."
msgstr "ВМ {} освобождена от {} пользователя(-ей)."

#: ../common/models/vm.py:362 ../common/models/vm.py:990
msgid "VM {} is clear from users."
msgstr "ВМ {} освобождена от пользователей."

#: ../common/models/vm.py:451 ../common/models/vm.py:757
msgid "There is no client for controller {}."
msgstr "Контролер {} не имеет подключения к ECP VeiL."

#: ../common/models/vm.py:493
msgid "Not enough free space on data pool."
msgstr "Недостаточно свободного места в пуле данных."

#: ../common/models/vm.py:497
#, python-brace-format
msgid "Failed to create VM. Error code: {create_response.error_code} Wait before next try."
msgstr "Не удалось создать ВМ. Код ошибки: {create_response.error_code} Подождите перед следующей попыткой."

#: ../common/models/vm.py:526
msgid "VM {} deleting cancelled by timeout."
msgstr "Удаление ВМ {} отменено по таймауту."

#: ../common/models/vm.py:551
msgid "VM multi-deletion task cancelled by timeout. Please see task details on VeiL ECP."
msgstr "Задача множественного удаления ВМ отменена по истечении времени ожидания. Пожалуйста посмотрите детали задачи на VeiL ECP."

#: ../common/models/vm.py:633
msgid "Error occurred during deleting Computers from Authentication Directory"
msgstr "Возникла ошибка во время удаления Computers из АД."

#: ../common/models/vm.py:689 ../web_app/controller/schema.py:417
#: ../web_app/journal/schema.py:306
msgid "No such event."
msgstr "Нет такого события."

#: ../common/models/vm.py:773
msgid "Remote task finished with error. Check ECP VeiL."
msgstr "Удаленная задача завершена с ошибкой. Проверьте ECP VeiL."

#: ../common/models/vm.py:788
msgid "VM {} is powered."
msgstr "ВМ {} включена."

#: ../common/models/vm.py:801
msgid "VM can`t be powered on or already powered."
msgstr "ВМ не включается или уже включена."

#: ../common/models/vm.py:808
msgid "VM {} already shutdown."
msgstr "ВМ {} уже выключена."

#: ../common/models/vm.py:817
msgid "VM {} is force shutdown."
msgstr "ВМ {} принудительно выключена."

#: ../common/models/vm.py:823
msgid "VM {} is shutdown."
msgstr "ВМ {} выключена."

#: ../common/models/vm.py:834 ../common/models/vm.py:869
msgid "VM {} is shutdown. Please power this."
msgstr "ВМ {} выключена. Пожалуйста включите её."

#: ../common/models/vm.py:844
msgid "VM {} was force reboot."
msgstr "ВМ {} принудительно перезагружена."

#: ../common/models/vm.py:850
msgid "VM {} was reboot."
msgstr "ВМ {} перезагружена."

#: ../common/models/vm.py:862
msgid "VM {} is suspended."
msgstr "ВМ {} приостановлена."

#: ../common/models/vm.py:882
msgid "Forbid create backup from a thin clone: {}."
msgstr "Запрещено создание резервной копии от тонкого клона: {}."

#: ../common/models/vm.py:894 ../pool_worker/pool_tasks.py:520
msgid "Creating backup finished with error."
msgstr "Создание резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:897
msgid "Backup for VM {} is created."
msgstr "Создана резервная копия для ВМ {}."

#: ../common/models/vm.py:954
msgid "Total size of pool {} increased."
msgstr "Увеличен максимальный размер пула {}."

#: ../common/models/vm.py:968 ../web_app/pool/schema.py:838
msgid "VM {} has been added to the pool {}."
msgstr "ВМ {} добавлена в пул {}."

#: ../common/models/vm.py:1001
msgid "Backup restore finished with error."
msgstr "Восстановление из резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:1004
msgid "Backup from VM {} restored to pool {} as {}."
msgstr "Резервная копия для ВМ {} восстановлена в пул {} с именем {}."

#: ../common/models/vm.py:1031
msgid "VM {} remote access enabled."
msgstr "Удаленный доступ ВМ {} включен."

#: ../common/models/vm.py:1040
msgid "Waiting Qemu guest agent for vm {}."
msgstr "Ожидание ответа Гостевого агента для ВМ {}."

#: ../common/models/vm.py:1059
msgid "Can`t set verbose name."
msgstr "Can`t set verbose name."

#: ../common/models/vm.py:1095
msgid "VM {} hostname setting task failed."
msgstr "Ошибка задания hostname ВМ {}."

#: ../common/models/vm.py:1100
msgid "VM {} hostname setting success."
msgstr "ВМ {} успешно задан hostname."

#: ../common/models/vm.py:1169
msgid "VM {} has been prepared."
msgstr "ВМ {} подготовлена."

#: ../common/models/vm.py:1172
msgid "VM preparation task finished with errors. Check ECP Veil."
msgstr "Задача подготовки ВМ завершена с ошибкой. Проверьте ECP VeiL."

#: ../common/models/vm.py:1174
msgid "ECP Veil failed to prepare VM."
msgstr "Не удалось подготовить ВМ на ECP VeiL."

#: ../common/models/vm.py:1197
msgid "{} preparation cancelled by timeout."
msgstr "подготовка {} отменена по таймауту."

#: ../common/models/vm.py:1209
msgid "VM {} preparation error."
msgstr "Ошибка подготовки ВМ {}."

#: ../common/models/vm_connection_data.py:34
#, python-brace-format
msgid "Vm connection data for VM {vm.verbose_name} and connection type {connection_type} added"
msgstr "Данные подключения для ВМ {vm.verbose_name} и типа подключения {connection_type} добавлены"

#: ../common/models/vm_connection_data.py:36
#: ../common/models/vm_connection_data.py:48
#, python-brace-format
msgid " Kwargs: {kwargs}"
msgstr ""

#: ../common/models/vm_connection_data.py:46
#, python-brace-format
msgid "Vm connection data for VM {vm.verbose_name} and connection type {self.connection_type} updated"
msgstr "Данные подключения для ВМ {vm.verbose_name} и типа подключения {self.connection_type} обновлены"

#: ../common/models/vm_connection_data.py:56
#, python-brace-format
msgid "Vm connection data for VM {vm.verbose_name} and connection type {self.connection_type} deleted"
msgstr "Данные подключения для ВМ {vm.verbose_name} и типа подключения {self.connection_type} удалены"

#: ../common/veil/auth/veil_jwt.py:50 ../common/veil/auth/veil_jwt.py:82
msgid "Token expired."
msgstr "Срок действия токена истек."

#: ../common/veil/auth/veil_jwt.py:77
msgid "Token invalid."
msgstr "Недействительный токен."

#: ../common/veil/auth/veil_jwt.py:139
msgid "Error with JWT decode."
msgstr "Ошибка JWT декодирования."

#: ../common/veil/auth/veil_jwt.py:149 ../common/veil/auth/veil_jwt.py:151
#: ../common/veil/auth/veil_jwt.py:153
msgid "Invalid authorization header."
msgstr "Неправильный заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:157
msgid "Missing authorization header."
msgstr "Пропущен заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:193 ../common/veil/veil_handlers.py:62
#: ../common/veil/veil_handlers.py:96
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: ../common/veil/veil_api.py:155
msgid "Can`t find VM {} on VeiL ECP."
msgstr "Не удалось найти ВМ {} на VeiL ECP."

#: ../common/veil/veil_api.py:166
msgid "Can`t find Tag {} on VeiL ECP."
msgstr "Не удалось найти Тег {} на VeiL ECP."

#: ../common/veil/veil_api.py:189
msgid "VeiL ECP {} request error."
msgstr "Ошибка запроса ECP VeiL {}."

#: ../common/veil/veil_decorators.py:43 ../common/veil/veil_decorators.py:49
#: ../web_app/auth/license/handlers.py:31 ../web_app/tests/test_auth_v2.py:116
msgid "Invalid permissions."
msgstr "Недостаточно прав."

#: ../common/veil/veil_decorators.py:44
msgid "IP: {}. username: {}."
msgstr "IP: {}. Пользователь: {}."

#: ../common/veil/veil_errors.py:154
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: ../common/veil/veil_errors.py:159
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: ../common/veil/veil_gino.py:82
msgid "Incorrect sort parameter {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/veil/veil_gino.py:92
msgid "Incorrect request parameter {}."
msgstr "Неверный параметр запроса {}."

#: ../common/veil/veil_gino.py:226
msgid "{} {} has been disabled."
msgstr "{} {} деактивирована."

#: ../common/veil/veil_gino.py:228
msgid "{} {} has`t been found in ECP VeiL. Switched to FAILED."
msgstr "{} {} не найдена на ECP VeiL. Переключена в статус с ошибкой."

#: ../common/veil/veil_gino.py:241
msgid "Group {} has been deleted."
msgstr "Группа {} удалена."

#: ../common/veil/veil_gino.py:245
msgid "Soft_delete exception: {}."
msgstr "Ошибка удаления: {}."

#: ../common/veil/veil_handlers.py:101
msgid "There is no pool with id: {}."
msgstr "Отсутствует пул с id: {}."

#: ../common/veil/veil_handlers.py:105
msgid "User {} has no VM on pool {}."
msgstr "У пользователя {} нет виртуальной машины в пуле {}."

#: ../common/veil/veil_handlers.py:159
msgid "Ws write error."
msgstr "Ошибка записи WS."

#: ../common/veil/veil_redis.py:354
msgid "Redis task waiting exception."
msgstr "Ошибка redis-задачи."

#: ../common/veil/veil_validators.py:30
msgid "Field \"{}\" - {}."
msgstr "Поле \"{}\" - {}."

#: ../monitor_worker/resources_monitor.py:100
msgid "{} is connected: {}."
msgstr "{} подключен: {}."

#: ../monitor_worker/resources_monitor.py:159
msgid "Resource monitor can`t connect to controller {}."
msgstr "Монитор ресурсов не может подключиться к контроллеру {}."

#: ../monitor_worker/resources_monitor.py:186
msgid "Closing ws connection {}."
msgstr "Закрываем WS соединение {}."

#: ../monitor_worker/resources_monitor_manager.py:67
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}."
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: ../monitor_worker/resources_monitor_manager.py:78
msgid "{}: Started."
msgstr "{}: Запущен."

#: ../monitor_worker/resources_monitor_manager.py:95
#, python-brace-format
msgid "{cls}: Controller {name} is already monitored."
msgstr "{cls}: Контроллер {name} уже отслеживается."

#: ../monitor_worker/resources_monitor_manager.py:103
#, python-brace-format
msgid "{cls}: resource monitor for controller {name} connected."
msgstr "{cls}: монитор ресурсов для контроллера {name} подключен."

#: ../pool_worker/pool_task_manager.py:64
msgid "Can`t launch task."
msgstr "Нет такого задания."

#: ../pool_worker/pool_task_manager.py:252
msgid "Task failed to start."
msgstr "Не удалось запустить задачу."

#: ../pool_worker/pool_tasks.py:103
msgid "Task '{}' started."
msgstr "Задача '{}' начала выполнение."

#: ../pool_worker/pool_tasks.py:108
msgid "Task '{}' finished successfully."
msgstr "Задача '{}' завершилась успешно."

#: ../pool_worker/pool_tasks.py:113
msgid "Task '{}' cancelled."
msgstr "Задача '{}' отменена."

#: ../pool_worker/pool_tasks.py:118
msgid "Task '{}' failed."
msgstr "Задача '{}' завершилась с ошибками."

#: ../pool_worker/pool_tasks.py:188
msgid "Creation of pool {}."
msgstr "Создание пула {}."

#: ../pool_worker/pool_tasks.py:211
msgid "Pool Creation cancelled."
msgstr "Создание пула отменено."

#: ../pool_worker/pool_tasks.py:231
msgid "Failed to init pool."
msgstr "Ошибка инициализации пула."

#: ../pool_worker/pool_tasks.py:252
msgid "Expanding of pool {}."
msgstr "Расширение пула {}."

#: ../pool_worker/pool_tasks.py:304
msgid "Automatic recreation of VM {} in the guest pool."
msgstr "Автоматическое пересоздание ВМ {} в гостевом пуле."

#: ../pool_worker/pool_tasks.py:326
msgid "VM creating error."
msgstr "Ошибка создания ВМ."

#: ../pool_worker/pool_tasks.py:344
msgid "Decreasing of pool {}."
msgstr "Уменьшение пула {}."

#: ../pool_worker/pool_tasks.py:384
msgid "Deleting of pool {}."
msgstr "Удаление пула {}."

#: ../pool_worker/pool_tasks.py:423
msgid "Preparation of vm {}."
msgstr "Подготовка ВМ {}."

#: ../pool_worker/pool_tasks.py:429
msgid "Another task works on this VM."
msgstr "ВМ заблокирована выполнением другой задачи."

#: ../pool_worker/pool_tasks.py:467
msgid "ECP VeiL domain request error."
msgstr "Ошибка запроса ВМ на ECP VeiL."

#: ../pool_worker/pool_tasks.py:470
msgid "Task has`t been created."
msgstr "Задача не была создана."

#: ../pool_worker/pool_tasks.py:487
msgid "VM remote access task {} for VM {} finished with error."
msgstr "Задача {} удаленного доступа к ВМ {} завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:504
msgid "Backup of {}."
msgstr "Бэкап {}."

#: ../pool_worker/pool_tasks.py:517
msgid "Wrong entity type."
msgstr "Неверный тип сущности."

#: ../pool_worker/pool_tasks.py:536
msgid "Removal of VMs from pool {}."
msgstr "Удаление ВМ из пула {}."

#: ../pool_worker/pool_tasks.py:582
msgid "Template change for pool {}."
msgstr "Изменение шаблона для пула {}."

#: ../pool_worker/pool_tasks.py:593 ../web_app/pool/schema.py:1741
msgid "VM {} is powered. Please shutdown this."
msgstr "ВМ {} включена. Пожалуйста выключите её."

#: ../pool_worker/pool_tasks.py:603 ../web_app/pool/schema.py:1769
msgid "VeiL ECP error: {}."
msgstr "Ошибка запроса ECP VeiL: {}."

#: ../pool_worker/pool_tasks.py:618
msgid "The template {} change and distribute this changes to thin clones."
msgstr "Шаблон {} изменен и распространен с изменениями на тонкие клоны."

#: ../pool_worker/pool_tasks.py:637
msgid "Preparation of VMs in pool {}."
msgstr "Подготовка ВМ в пуле {}."

#: ../pool_worker/pool_tasks.py:659
#, python-brace-format
msgid "Synchronization of AD group {group.verbose_name}."
msgstr "Синхронизация группы AD {group.verbose_name}."

#: ../pool_worker/pool_tasks.py:665
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:35
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:216
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:272
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:444
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:496
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:516
msgid "No such Authentication Directory."
msgstr "Такая Authentication Directory отсутствует."

#: ../pool_worker/vm_manager.py:112
msgid "Keep vms on task error."
msgstr "Сохранить ВМ при ошибке задачи."

#: ../pool_worker/vm_manager.py:149
msgid "Synchronize vm data task error."
msgstr "Ошибка задачи синхронизации данных виртуальной машины."

#: ../pool_worker/vm_manager.py:202
msgid "Action upon user disconnect completed. Action: {}. VM: {}. Result: {}."
msgstr "Действие при отключении пользователя завершено. Действие: {}. ВМ: {}. Результат: {}."

#: ../pool_worker/vm_manager.py:208
msgid "Vm post disconnect action error."
msgstr "Ошибка действия ВМ после отключения."

#: ../pool_worker/vm_manager.py:269
msgid "_do_actions_when_user_disconnects_from_vm error."
msgstr "Ошибка _do_actions_when_user_disconnects_from_vm."

#: ../web_app/app.py:121
msgid "VDI broker stopped."
msgstr "VDI брокер остановлен."

#: ../web_app/app.py:133
msgid "{} instance(s) of VDI broker web application launched on {}."
msgstr "Веб-приложение брокера VDI запущено в {} экземпляре(ах) на машине {}."

#: ../web_app/app.py:138
msgid "Authentication system is disabled."
msgstr "Система аутентификации выключена."

#: ../web_app/app.py:142
msgid "The license is expired on {}. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла на машине {}. Некоторые функции будут заблокированы. Свяжитесь с вашим поставщиком."

#: ../web_app/app.py:146
msgid "DEBUG mode is enabled."
msgstr "Режим отладки включен."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:41
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на службу каталогов должна начинаться с ldap(s)://."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:48
msgid "Verbose name should not be empty."
msgstr "Имя не должно быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:55
msgid "Value should be 1-63 latin characters, -, . or _."
msgstr "Значение должно быть в диапазоне от 1-63 латинских символа, -, . или _."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:76
#: ../web_app/auth/group_schema.py:48
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:78
msgid "groups list is empty."
msgstr "Список групп пуст."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:85
msgid "No such mapping."
msgstr "Нет такого отображения."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:90
msgid "DC should not be empty."
msgstr "Класс объекта домена не должен быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:212
msgid "Specify id."
msgstr "Укажите id."

#: ../web_app/auth/group_schema.py:26 ../web_app/auth/group_schema.py:163
msgid "No such group."
msgstr "Отсутствует такая группа."

#: ../web_app/auth/group_schema.py:34
msgid "verbose name must be <= 128 characters."
msgstr "имя должно быть <= 128 символов."

#: ../web_app/auth/group_schema.py:35
msgid "verbose_name is empty."
msgstr "имя пустое."

#: ../web_app/auth/group_schema.py:50
msgid "users list is empty."
msgstr "список пользователей пуст."

#: ../web_app/auth/group_schema.py:56
msgid "Description length must be <= 255 characters."
msgstr "Описание должно быть <= 255 символам."

#: ../web_app/auth/group_schema.py:199
msgid "Group {} already exists."
msgstr "Группа {} уже существует."

#: ../web_app/auth/group_schema.py:241
msgid "Specify Group.id or Group.ad_guid."
msgstr "Укажите Group.id или Group.ad_guid."

#: ../web_app/auth/group_schema.py:243
msgid "Specify Group.id or Group.ad_guid. Not both."
msgstr "Укажите Group.id или Group.ad_guid. Не оба."

#: ../web_app/auth/handlers.py:26
msgid "Missing request body."
msgstr "Отсутствует тело запроса."

#: ../web_app/auth/handlers.py:28
msgid "Missing username and password."
msgstr "Отсутствует имя пользователя и пароль."

#: ../web_app/auth/handlers.py:34
msgid "Missing username."
msgstr "Отсутствует имя пользователя."

#: ../web_app/auth/handlers.py:36
msgid "Missing password."
msgstr "Отсутствует пароль."

#: ../web_app/auth/handlers.py:44
msgid "External auth system is disabled. Check broker settings."
msgstr "Внешняя служба авторизации отключена. Проверьте настройки брокера."

#: ../web_app/auth/handlers.py:48
msgid "PAM or LOCAL auth only. Check broker settings."
msgstr "Проверьте настройки брокера. Разрешена только pam ИЛИ локальная авторизация."

#: ../web_app/auth/handlers.py:58
msgid "Auth system is disabled. Check broker settings."
msgstr "Проверьте настройки брокера. Система аутентификации отключена."

#: ../web_app/auth/handlers.py:89 ../web_app/auth/handlers.py:108
msgid "Authentication failed for user: {}."
msgstr "Ошибка авторизации пользователя: {}."

#: ../web_app/auth/handlers.py:123
#, python-brace-format
msgid "Missing VeiL Connect version. {base_error_msg}."
msgstr "Не указана версия VeiL Connect. {base_error_msg}."

#: ../web_app/auth/handlers.py:129
#, python-brace-format
msgid "Version {veil_connect_version} is not supported. {base_error_msg}."
msgstr "Версия {veil_connect_version} не поддерживается. {base_error_msg}."

#: ../web_app/auth/handlers.py:135 ../web_app/thin_client_api/handlers.py:466
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: ../web_app/auth/handlers.py:144
msgid "User {} logged out."
msgstr "Пользователь {} вышел из системы."

#: ../web_app/auth/license/handlers.py:46
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: ../web_app/auth/license/handlers.py:57
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: ../web_app/auth/user_schema.py:33 ../web_app/auth/user_schema.py:272
#: ../web_app/thin_client_api/schema.py:263
msgid "No such user."
msgstr "Нет такого пользователя."

#: ../web_app/auth/user_schema.py:42
msgid "username must be at least 2 character."
msgstr "имя пользователя должно быть не менее 2 символов."

#: ../web_app/auth/user_schema.py:52
msgid "username must contain letters, digits, _, +, begin from letter and can't contain any spaces."
msgstr "имя пользователя должно состоять из букв, цифр, _, +, начинаться с буквы и не содержать пробелов."

#: ../web_app/auth/user_schema.py:61
msgid "Email {} is already busy."
msgstr "Email {} занят."

#: ../web_app/auth/user_schema.py:74
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: ../web_app/auth/user_schema.py:89
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: ../web_app/auth/user_schema.py:95
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: ../web_app/auth/user_schema.py:268
msgid "Specify id or username."
msgstr "Укажите id или имя пользователя."

#: ../web_app/auth/user_schema.py:367
#, python-brace-format
msgid "Can not delete administrator account {username}."
msgstr "Невозможно удалить учетную запись администратора {username}."

#: ../web_app/auth/user_schema.py:374
#, python-brace-format
msgid "User {username} was deleted."
msgstr "Пользователь {username} был удален."

#: ../web_app/auth/user_schema.py:544
msgid "Can`t remove permission(s) {} because they are granted to groups of user {}."
msgstr "Невозможно удалить разрешения {}, так как они выданы группам, в которых состоит пользователь."

#: ../web_app/controller/resource_schema.py:304
msgid "{} is unreachable on ECP VeiL."
msgstr "{} недоступен на ECP VeiL."

#: ../web_app/controller/resource_schema.py:713 ../web_app/pool/schema.py:1679
msgid "Cant create CD-ROM for powered domain {}."
msgstr "Невозможно создать CD-ROM для включенной виртуальной машины {}."

#: ../web_app/controller/resource_schema.py:722 ../web_app/pool/schema.py:1688
msgid "Creating a CD-ROM on the virtual machine {}."
msgstr "Создание CD-ROM на виртуальной машине {}."

#: ../web_app/controller/schema.py:39
msgid "name can`t be empty."
msgstr "имя не может быть пустым."

#: ../web_app/controller/schema.py:48
msgid "name `{}` is busy."
msgstr "имя `{}` уже используется."

#: ../web_app/controller/schema.py:56
msgid "address can`t be empty."
msgstr "адресс не может быть пустым."

#: ../web_app/controller/schema.py:65
msgid "address `{}` is busy."
msgstr "адресс `{}` уже используется."

#: ../web_app/controller/schema.py:72
msgid "token can`t be empty."
msgstr "токен не может быть пустым."

#: ../web_app/controller/schema.py:457 ../web_app/controller/schema.py:490
msgid "Connection to ECP has been failed."
msgstr "Соединение с ECP не удалось."

#: ../web_app/front_ws_api/handlers.py:46
msgid "WebSocket opened."
msgstr "WebSocket открыт."

#: ../web_app/front_ws_api/handlers.py:51
msgid "Message: {}."
msgstr "Сообщение: {}."

#: ../web_app/front_ws_api/handlers.py:75
msgid "WS listener error."
msgstr "Ошибка сервиса прослушивания WS."

#: ../web_app/front_ws_api/handlers.py:76
msgid "Unknown subscription source."
msgstr "Неизвестный источник подписки."

#: ../web_app/front_ws_api/handlers.py:93
msgid "Already subscribed."
msgstr "Уже подписан."

#: ../web_app/front_ws_api/handlers.py:100
msgid "Not subscribed."
msgstr "Не подписан."

#: ../web_app/journal/schema.py:414
msgid "Journal is exported."
msgstr "Журнал экспортирован."

#: ../web_app/pool/schema.py:85 ../web_app/pool/schema.py:582
#: ../web_app/pool/schema.py:604
msgid "No such pool."
msgstr "Нет такого пула."

#: ../web_app/pool/schema.py:96
msgid "Pool name must contain only characters, digits and -."
msgstr "Имя пула должно содержать только буквы, цифры и -."

#: ../web_app/pool/schema.py:112
msgid "Template name of VM must contain only characters, digits, -. Template name length must be in [{} {}] interval."
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, -. Длина шаблонного имени должна быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:123
msgid "Initial number of VM must be in {}-{} interval."
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:147
msgid "Reserve size of VMs can not be more than maximal number of Vms."
msgstr "Резервное число ВМ не может быть больше максимального числа ВМ."

#: ../web_app/pool/schema.py:152
msgid "Reserve size of VM must be in {}-{} interval."
msgstr "Резервное число ВМ должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:181
msgid "Maximal number of created VM can not be less than initial number of VM."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ."

#: ../web_app/pool/schema.py:187
msgid "Maximal number of created VM must be in [{} {}] interval."
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:194
msgid "Maximal number of created VMs can not be less than current amount of Vms."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше текущего числа ВМ."

#: ../web_app/pool/schema.py:213
msgid "Increase step must be positive and less or equal to total_size."
msgstr "Шаг увеличения должен быть положительным и меньше или равен общему количеству."

#: ../web_app/pool/schema.py:217
msgid "Increase step must be less than {}."
msgstr "Шаг увеличения должен быть меньше {}."

#: ../web_app/pool/schema.py:225
msgid "Connection type cannot be empty."
msgstr "Тип подключения не может быть пустым."

#: ../web_app/pool/schema.py:230
msgid "Vm action timeout must be a positive number."
msgstr "Время ожидания действия ВМ должно быть положительным числом."

#: ../web_app/pool/schema.py:240
msgid "Vm disconnect action RECREATE is not allowed for pool type {}."
msgstr "Действие пересоздания ВМ при отключении не разрешено для пула типа {}."

#: ../web_app/pool/schema.py:244
msgid "Guest pool must have vm disconnect action RECREATE."
msgstr "В гостевом пуле должно быть действие пересоздания ВМ при отключении."

#: ../web_app/pool/schema.py:247
msgid "RDS pool is not allowed to have vm disconnect actions."
msgstr "Пул RDS не может иметь действия при отключении ВМ."

#: ../web_app/pool/schema.py:261
msgid "Connection types {} are not supported."
msgstr "Типы подключения {} не поддерживаются."

#: ../web_app/pool/schema.py:267
#, python-brace-format
msgid "Vm connection data with id {id_} does not exist."
msgstr "Данные подключения с id {id_} не существуют."

#: ../web_app/pool/schema.py:447 ../web_app/thin_client_api/handlers.py:364
msgid "VM is unreachable on ECP VeiL."
msgstr "ВМ недоступна на ECP VeiL."

#: ../web_app/pool/schema.py:630
msgid "Pool {} has been restored."
msgstr "Ошибки пула {} сброшены."

#: ../web_app/pool/schema.py:636
msgid "Pool {} is in service mode."
msgstr "Пул {} находится в сервисном режиме."

#: ../web_app/pool/schema.py:640
msgid "Pool {} is already active."
msgstr "Пул {} уже активирован."

#: ../web_app/pool/schema.py:737
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: ../web_app/pool/schema.py:784
msgid "rds_vm or rds_vms must be specified"
msgstr "rds_vm или rds_vms должны быть указаны"

#: ../web_app/pool/schema.py:821
msgid "VM {} is already in one of pools."
msgstr "Виртуальная машина {} уже в одном из пулов."

#: ../web_app/pool/schema.py:890
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:924
msgid "Failed to update RDS pool {}. Name must be unique."
msgstr "Ошибка редактирования пула приложений {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:958
msgid "Can not expand pool {} because it reached its total_size."
msgstr "Не удается расширить пул {} т.к. достигнут максимальный размер."

#: ../web_app/pool/schema.py:972
msgid "Another task works on pool {}: {}."
msgstr "Другая задача выполняется над пулом {}."

#: ../web_app/pool/schema.py:980
msgid "Increase_step {}."
msgstr "Шаг расширения пула {}."

#: ../web_app/pool/schema.py:982
msgid "Expansion of pool {} requested."
msgstr "Запрошено расширение пула {}."

#: ../web_app/pool/schema.py:1101
msgid "Failed to create pool {}."
msgstr "Ошибка создания пула {}."

#: ../web_app/pool/schema.py:1165
msgid "Failed to update total_size. Task status is {}. Check journal for more info."
msgstr "Не удалось обновить максимальный размер. Статус задачи: {}. Проверьте журнал для получения дополнительной информации."

#: ../web_app/pool/schema.py:1208
msgid "Failed to update pool {}. Name must be unique."
msgstr "Ошибка редактирования пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:1235
msgid "Settings of pool {} is copied."
msgstr "Настройки пула {} скопированы."

#: ../web_app/pool/schema.py:1379
msgid "There is no VM {}."
msgstr "Нет ВМ {}."

#: ../web_app/pool/schema.py:1391
msgid "Impossible to assign more than 1 user to VM {} in guest pool."
msgstr "Невозможно назначить более 1 пользователя на ВМ {} в гостевом пуле."

#: ../web_app/pool/schema.py:1398 ../web_app/pool/schema.py:1436
msgid "Provide users list or username."
msgstr "Укажите список пользователей или имя пользователя."

#: ../web_app/pool/schema.py:1408
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: ../web_app/pool/schema.py:1475
msgid "Another task works on VM {}."
msgstr "Другая задача выполняется над ВМ {}."

#: ../web_app/pool/schema.py:1632
msgid "Only VM with Windows OS can be in domain."
msgstr "Только ВМ на ОС Windows могут находиться в домене."

#: ../web_app/pool/schema.py:1753
msgid "Prohibited creating template from the thin clone."
msgstr "Запрещено создание шаблона из тонкого клона."

#: ../web_app/pool/schema.py:1772
msgid "Vm {} has converted to template {}."
msgstr "ВМ {} преобразована в шаблон {}."

#: ../web_app/pool/schema.py:1800
#, python-brace-format
msgid "Vm connection data for vm_id {vm_id} and connection_type {connection_type} already exists."
msgstr "Данные подключения для vm_id {vm_id} и типа подключения {connection_type} уже существуют."

#: ../web_app/settings/schema.py:24
msgid "Apache server."
msgstr "Сервер Apache."

#: ../web_app/settings/schema.py:25 ../web_app/settings/schema.py:26
msgid "Database."
msgstr "База данных."

#: ../web_app/settings/schema.py:29
msgid "Monitor worker."
msgstr "Монитор состояния компонентов."

#: ../web_app/settings/schema.py:30
msgid "Task worker."
msgstr "Обработчик задач."

#: ../web_app/settings/schema.py:31
msgid "Web application."
msgstr "Веб-приложение."

#: ../web_app/settings/schema.py:134
msgid "Unable to get services information. {}."
msgstr "Невозможно получить информацию о сервисах. {}."

#: ../web_app/settings/schema.py:138
msgid "No services launched."
msgstr "Никаких сервисов не запущено."

#: ../web_app/settings/schema.py:151
msgid "Output parsing error. {}."
msgstr "Ошибка вывода парсинга. {}."

#: ../web_app/settings/schema.py:289
msgid "Invalid service name {}."
msgstr "Недействительное название службы {}."

#: ../web_app/settings/schema.py:306
msgid "Error occurred during service action executing. {}."
msgstr "Ошибка при выполнении действия сервиса. {}."

#: ../web_app/settings/schema.py:311
msgid "Executed action {} for service {}."
msgstr "Выполнено действие {} для сервиса {}."

#: ../web_app/settings/schema.py:330
msgid "Unable to check status of service {}."
msgstr "Невозможно проверить статус сервиса {}."

#: ../web_app/settings/schema.py:344
msgid "Cache is cleared."
msgstr "Кэш очищен."

#: ../web_app/statistics/schema.py:262
msgid "Pool with id {} does not exist."
msgstr "Пула с id {} не существует."

#: ../web_app/statistics/schema.py:273
msgid "Failed to generate statistics report."
msgstr "Ошибка создания отчета статистики."

#: ../web_app/task/schema.py:115
msgid "No such task."
msgstr "Нет такого задания."

#: ../web_app/task/schema.py:140
msgid "No such task or status of task {} is not {}."
msgstr "Нет такого задания или статус задания {} не {}."

#: ../web_app/task/schema.py:152
msgid "Task '{} ({})' is requested to be cancelled by user {}."
msgstr "Задача '{} ({})' запрошена для отмены пользователем {}."

#: ../web_app/task/schema.py:172
msgid "No controller with id {}."
msgstr "Нет контроллера с id {}."

#: ../web_app/task/schema.py:180
msgid "Tasks associated with controller {} are requested to be cancelled by user {}."
msgstr "Задачи, связанные с контроллером {}, запрошены для отменены пользователем {}."

#: ../web_app/thin_client_api/handlers.py:66
msgid "User {} requested pools data."
msgstr "Пользователь {} запросил список пулов."

#: ../web_app/thin_client_api/handlers.py:106
msgid "Looking for active RDS Connection Broker."
msgstr "Поиск активного RDS брокера подключений."

#: ../web_app/thin_client_api/handlers.py:110
msgid "No active Remote Desktop Connection Broker found."
msgstr "Активные RDS брокеры подключений не найдены."

#: ../web_app/thin_client_api/handlers.py:118
msgid "Fetching published applications data."
msgstr "Получение данных об опубликованных приложениях."

#: ../web_app/thin_client_api/handlers.py:123
msgid "Unable to get list of published applications. {}."
msgstr "Невозможно получить список опубликованных приложений. {}."

#: ../web_app/thin_client_api/handlers.py:134
msgid "Looking for machine."
msgstr "Поиск ВМ."

#: ../web_app/thin_client_api/handlers.py:144
msgid "The pool is busy. Try again in 1 minute."
msgstr "Пул занят. Попробуйте снова через 1 минуту."

#: ../web_app/thin_client_api/handlers.py:159
msgid "The pool doesn`t have free machines. Try again after 5 minutes."
msgstr "В пуле нет свободных машин. Повторите попытку через 5 минут."

#: ../web_app/thin_client_api/handlers.py:162
msgid "The pool doesn`t have free machines."
msgstr "В пуле нет свободных машин."

#: ../web_app/thin_client_api/handlers.py:169
msgid "Machine is being prepared."
msgstr "ВМ подготавливается."

#: ../web_app/thin_client_api/handlers.py:176
msgid "Connection data resolving (address/port)."
msgstr "Получение данных подключения (адрес/порт)."

#: ../web_app/thin_client_api/handlers.py:201
msgid "User {} connected to pool {}."
msgstr "Пользователь {} подключился к пулу {}."

#: ../web_app/thin_client_api/handlers.py:296
msgid "The remote controller is unavailable."
msgstr "Контроллер недоступен."

#: ../web_app/thin_client_api/handlers.py:329
msgid "The controller didn`t provide a VM address. Try again in 1 minute."
msgstr "Контроллер не передал адрес ВМ. Попробуйте снова через 1 минуту."

#: ../web_app/thin_client_api/handlers.py:343
msgid "Wrong protocol."
msgstr "Неверный протокол."

#: ../web_app/thin_client_api/handlers.py:367
msgid "Controller did not reply. Check if it is available."
msgstr "Контроллер не ответил. Проверьте, доступен ли он."

#: ../web_app/thin_client_api/handlers.py:389
msgid "Setting time zone."
msgstr "Настройки временной зоны."

#: ../web_app/thin_client_api/handlers.py:438
msgid "Failed to set time zone for vm {}."
msgstr "Ошибка установки временной зоны для ВМ {}."

#: ../web_app/thin_client_api/handlers.py:458
msgid "VM address resolving. Attempt number {}."
msgstr "Получение адреса ВМ. Попытка номер {}."

#: ../web_app/thin_client_api/handlers.py:469
msgid "Pool not found."
msgstr "Пул не найден."

#: ../web_app/thin_client_api/handlers.py:478
msgid "The pool doesnt support connection type {}."
msgstr "Пул не поддерживает тип соединения {}."

#: ../web_app/thin_client_api/handlers.py:532
msgid "User {} executed action {} on VM {}."
msgstr "Пользователь {} выполнил действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:534
msgid "User {} failed to execute action {} on VM {}."
msgstr "Пользователю {} не удалось выполнить действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:619
msgid "Message can not be empty."
msgstr "Сообщение не может быть пустым."

#: ../web_app/thin_client_api/handlers.py:640
msgid "Wrong message format."
msgstr "Неправильны формат сообщения."

#: ../web_app/thin_client_api/handlers.py:721
msgid "Ws: on_message: error."
msgstr "Ws: on_message: ошибка."

#: ../web_app/thin_client_api/handlers.py:918
msgid "VM {} is not registered in VDI broker."
msgstr "ВМ {} не зарегистрирована в брокере VDI."

#: ../web_app/thin_client_api/schema.py:160
msgid "No connection information with id {}."
msgstr "Нет информации о подключении с id {}."

#: ../web_app/thin_client_api/schema.py:254
msgid "All connections."
msgstr "Все подключения."

#: ../web_app/thin_client_api/schema.py:257
msgid "Connection id: {}."
msgstr "id подключения: {}."

#: ../web_app/thin_client_api/schema.py:264
msgid "Connections of user: {}."
msgstr "Подключения пользователя {}."

#: ../web_app/thin_client_api/schema.py:268
msgid "Thin client disconnect requested."
msgstr "Запрошено отключение тонкого клиента."

#: ../web_app/thin_client_api/schema.py:305
msgid "User {} does not exist."
msgstr "Не существует пользователя {}."

#: ../web_app/vm_type.py:252
msgid "Missing connection spice data."
msgstr "Пропущены данные для spice соединения."

#: ../web_app/vm_type.py:266
msgid "Missing connection vnc data."
msgstr "Пропущены данные для vnc соединения."

#~ msgid "something other."
#~ msgstr "что-то другое."

#~ msgid "Group {} is removed for user {}."
#~ msgstr "Группа {} удалена у пользователя {}."

#~ msgid "One-time password error for user: {}."
#~ msgstr "Ошибка одноразового пароля для пользователя: {}."

#~ msgid "User {} do not have a secret code for 2fa auth. Please generate this in settings of user."
#~ msgstr "У пользователя {} нет секретного кода для двухфакторной аутентификации. Пожалуйста, сгенерируйте это в настройках пользователя."

#~ msgid "2fa auth error for user: {}."
#~ msgstr "Ошибка двухфакторной аутентификации для пользователя: {}."

#~ msgid "StaticPool: Create Pool."
#~ msgstr "Статический пул: создание пула."

#~ msgid "StaticPool: Create StaticPool."
#~ msgstr "Статический пул: создание статического пула."

#~ msgid "StaticPool: Create VMs."
#~ msgstr "Статический пул: создание виртуальных машин."

#~ msgid "Can`t connect to {}."
#~ msgstr "Не удается подключиться к {}."

#~ msgid "Pool {} has been deactivated."
#~ msgstr "Пул {} деактивирован."

#~ msgid "Controller has not free space for creating new VM."
#~ msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#~ msgid "Something went wrong. Interrupt while."
#~ msgstr "Что-то пошло не так. Прерываем while."

#~ msgid "User {} created with role {}."
#~ msgstr "Пользователь {} создан с ролью {}."

#~ msgid "  Duration: {}."
#~ msgstr "  Продолжительность: {}."

#~ msgid "Attempts to create VM {} have been exhausted."
#~ msgstr "Превышен лимит попыток создания ВМ {}."

#~ msgid "Unknown node {}."
#~ msgstr "Неизвестный узел {}."

#~ msgid "Controller can`t create VM. Unknown node."
#~ msgstr "Контроллер не может создать ВМ. Неизвестный узел."

#~ msgid "Roles: {} was deleted to pool {}."
#~ msgstr "Роли: {} удалены в пуле {}."

#~ msgid "Pool already has role."
#~ msgstr "Пул уже имеет роль."

#~ msgid "Role {} has been set to pool {}."
#~ msgstr "Роль {} добавлена в пул {}."

#~ msgid "Critical controller error."
#~ msgstr "Критическая ошибка контроллера."

#~ msgid "ECP VeiL controller {} error."
#~ msgstr "Ошибка контроллера ECP VeiL {}."

#~ msgid "Failed to update automated pool {}. Name must be unique."
#~ msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#~ msgid "Failed to create automated pool {}."
#~ msgstr "Ошибка создания автоматического пула {}."

#~ msgid "Update Pool values for AutomatedPool {}."
#~ msgstr "Обновление значений пула для автоматического пула {}."

#~ msgid "Demo version."
#~ msgstr "Демонстрационная версия."

#~ msgid "VM {} AD group including successful."
#~ msgstr "ВМ {} успешно заведена в контейнер/группу AD."

#~ msgid "VM {} active directory group including error."
#~ msgstr "Ошибка ввода ВМ {} в группу AD."

#~ msgid "Active directory object has no service username or password. Including skipped."
#~ msgstr "У службы каталогов не указаны имя пользователя и пароль. Пропускаем."

#~ msgid "Expansion of guest pool {} requested."
#~ msgstr "Запрошено расширение гостевого пула {}."

#~ msgid "Another task works on pool {} before creating new blank VM."
#~ msgstr "Другая задача выполняется над пулом {} перед созданием новой пустой ВМ."

#~ msgid "User {} password setting error."
#~ msgstr "Ошибка задания пароля пользователя {}."

#~ msgid "Redis waiting exception."
#~ msgstr "Ошибка Redis."

#~ msgid "username {} must contain >= 3 chars (letters, digits, _, -, +), begin from letter and can't contain any spaces."
#~ msgstr "имя пользователя {} должно быть >= 3 символов (буквы, цифры, _, -, +), начинаться с буквы и не содержать пробелов."

#~ msgid "Password {} contains invalid characters."
#~ msgstr "Пароль {} содержит недопустимые символы."

#~ msgid "Check pool settings."
#~ msgstr "Проверьте настройки пула."

#~ msgid "VM {} has been not prepared."
#~ msgstr "ВМ {} не подготовлена."

#~ msgid "VM {} AD inclusion skipped."
#~ msgstr "Заведение ВМ {} в домен пропущено."

#~ msgid "VM {} AD inclusion success."
#~ msgstr "ВМ {} успешно заведена в AD."

#~ msgid "VM {} domain including task failed."
#~ msgstr "Ошибка включения ВМ {} в домен."

#~ msgid "VM {} failed to receive DHCP ip address ({})."
#~ msgstr "ВМ {} не получила IP адрес по DHCP ({})."

#~ msgid "Unsupported pool type."
#~ msgstr "Неподдерживаемый тип пула."

#~ msgid "Password must contain letters and/or digits, special characters; also be at least 8 characters."
#~ msgstr "Пароль должен содержать разнорегистровые буквы и/или цифры, специальные символы; также должен быть не менее 8 символов."

#~ msgid "Invalid license key."
#~ msgstr "Неудачная попытка загрузить лицензионный ключ."

#~ msgid "Pool initialization VM(s) preparation error."
#~ msgstr "В момент инициализации пула подготовка виртуальных машин завершилась с ошибкой."

#~ msgid "Possibly blocked by active task on ECP. Wait before next try."
#~ msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."
