# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <e.gareev@mashtab.org>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-06-25 14:58+0300\n"
"PO-Revision-Date: 2020-03-16 17:13+0300\n"
"Last-Translator: Emil <e.gareev@mashtab.org>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: app.py:111
msgid "Stopping Tornado VDI"
msgstr "Остановка Tornado VDI"

#: app.py:113
msgid "Stopping redis"
msgstr "Остановка redis"

#: app.py:116
msgid "Stopping resources_monitor_manager"
msgstr "Остановка менеджера мониторинга ресурсов"

#: app.py:119
msgid "Stopping GINO"
msgstr "Остановка GINO"

#: app.py:122
msgid "Stopping IOLoop"
msgstr "Остановка IOLoop"

#: app.py:125
msgid "Tornado VDI stopped"
msgstr "Tornado VDI остановлен"

#: app.py:138
msgid "Tornado VDI started"
msgstr "Tornado VDI запущен"

#: app.py:141
msgid "Auth is disabled. Enable on production!"
msgstr "Используйте выключенную авторизацию только в режиме отладки!"

#: app.py:145
msgid "The license is expired. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла. Некоторые функции будут недоступны."

#: app.py:147
msgid "License status: {}, expiration time: {}, thin clients limit: {}"
msgstr "Статус лицензии: {}, дата истечения: {}, лимит тонких клиентов: {}"

#: auth/authentication_directory/auth_dir_schema.py:32
#: auth/authentication_directory/auth_dir_schema.py:219
#: auth/authentication_directory/auth_dir_schema.py:236
#: auth/authentication_directory/auth_dir_schema.py:283
#: auth/authentication_directory/auth_dir_schema.py:441
msgid "No such Authentication Directory."
msgstr "Отсутствует такая директория авторизации."

#: auth/authentication_directory/auth_dir_schema.py:38
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на директорию авторизации должна начинаться с ldap(s)://."

#: auth/authentication_directory/auth_dir_schema.py:45
msgid "Verbose name should not be empty."
msgstr "Имя verbose не должно быть пустым."

#: auth/authentication_directory/auth_dir_schema.py:53
msgid "'domain name' should be a string split by a dot."
msgstr "'имя домена' должно быть разделено точкой."

#: auth/authentication_directory/auth_dir_schema.py:68 auth/group_schema.py:44
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: auth/authentication_directory/auth_dir_schema.py:70
msgid "groups list is empty."
msgstr "Список групп пуст."

#: auth/authentication_directory/auth_dir_schema.py:77
msgid "No such mapping."
msgstr "Нет такого отображения."

#: auth/authentication_directory/auth_dir_schema.py:215
msgid "Specify id."
msgstr "Укажите ID."

#: auth/authentication_directory/auth_dir_schema.py:284
msgid "Authentication directory"
msgstr "Директория авторизации"

#: auth/authentication_directory/auth_dir_schema.py:390
msgid "In authentication directory {} mapping"
msgstr "В директории авторизации {} отображение"

#: auth/authentication_directory/models.py:131 tests/test_auth_dir.py:120
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной директории авторизации."

#: auth/authentication_directory/models.py:154
msgid "Authentication directory {} is created"
msgstr "Директория авторизации {} создана"

#: auth/authentication_directory/models.py:192
msgid "Id: {}. Arguments: {}"
msgstr "Id: {}. Аргументы: {}"

#: auth/authentication_directory/models.py:193
msgid "Values for auth directory is updated"
msgstr "Values for auth directory is updated"

#: auth/authentication_directory/models.py:203
#: auth/authentication_directory/models.py:728 auth/models.py:426
#: controller/models.py:313 pool/models.py:481 vm/models.py:106
msgid "{} {} had remove."
msgstr "Выполнено удаление: {} {}."

#: auth/authentication_directory/models.py:224
msgid "Arguments: {} of group: {}"
msgstr "Аргументы: {} группы: {}"

#: auth/authentication_directory/models.py:225
msgid "Mapping for auth directory {} is created"
msgstr "Отображение для директории авторизации {} создано"

#: auth/authentication_directory/models.py:244
msgid "New arguments: {} of group: {}"
msgstr "Новые аргументы: {} группы: {}"

#: auth/authentication_directory/models.py:245
msgid "Mapping for auth directory {} is updated"
msgstr "Mapping for auth directory {} is updated"

#: auth/authentication_directory/models.py:266
#: auth/authentication_directory/models.py:451
msgid "Authentication directory server {} is down."
msgstr "Сервер директории авторизации {} не работает."

#: auth/authentication_directory/models.py:273
msgid "Authentication directory server {} is connected"
msgstr "Сервер директории авторизации {} подключен"

#: auth/authentication_directory/models.py:308
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: auth/authentication_directory/models.py:380
#: auth/authentication_directory/models.py:393 tests/test_auth_v2.py:109
msgid "No authentication directory controllers."
msgstr "Переданная запись отсутствует в системе."

#: auth/authentication_directory/models.py:419
msgid "Invalid credentials (ldap): {}"
msgstr "Неверные учетные данные (ldap): {}"

#: auth/authentication_directory/models.py:426
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: auth/authentication_directory/models.py:446
msgid "Authentication directory server {} has bad auth info."
msgstr "Не удалось подключиться к серверу Authentication Directory {}"

#: auth/authentication_directory/models.py:514
#: auth/authentication_directory/models.py:593
msgid "Fail to connect to Authentication Directory. Check service information"
msgstr "Ошибка подключения к Authentication Directory."

#: auth/authentication_directory/models.py:735 vm/models.py:113
msgid "Soft_delete exception: {}"
msgstr "Ошибка удаления: {}"

#: auth/group_schema.py:26 auth/group_schema.py:105
msgid "No such group."
msgstr "Отсутствует такая группа."

#: auth/group_schema.py:34
msgid "verbose name must me <= 128 characters."
msgstr "verbose name должен быть <= 128 символов"

#: auth/group_schema.py:35
msgid "verbose_name is empty."
msgstr "verbose name пустое."

#: auth/group_schema.py:46
msgid "users list is empty."
msgstr "список пользователей пуст."

#: auth/group_schema.py:51
msgid "Last name length must be <= 255 characters."
msgstr "Фамилия должна быть <= 255 символам."

#: auth/group_schema.py:168
msgid "Specify Group.id or Group.ad_guid."
msgstr "Specify Group.id or Group.ad_guid."

#: auth/group_schema.py:170
msgid "Specify Group.id or Group.ad_guid. Not both."
msgstr "Укажите Group.id или Group.ad_guid. Не оба сразу."

#: auth/group_schema.py:174
msgid "No such Group."
msgstr "Отсутствует такая группа."

#: auth/group_schema.py:175
msgid "Group"
msgstr "Группа"

#: auth/handlers.py:23
msgid "Missing request body"
msgstr "Отсутствует тело запроса"

#: auth/handlers.py:25
msgid "Missing username and password"
msgstr "Отсутствует имя пользователя и пароль"

#: auth/handlers.py:30
msgid "Missing username"
msgstr "Отсутствует имя пользователя"

#: auth/handlers.py:32 tests/test_auth_v2.py:51
msgid "Missing password"
msgstr "Отсутствует пароль"

#: auth/handlers.py:42 tests/test_auth_v2.py:35 tests/test_auth_v2.py:43
msgid "Invalid credentials"
msgstr "Неверные полномочия"

#: auth/handlers.py:49
#, python-brace-format
msgid "Authentication failed: {err}"
msgstr "Ошибка авторизации {err}"

#: auth/handlers.py:51
#, python-brace-format
msgid " for user {username}"
msgstr " для пользователя {username}"

#: auth/handlers.py:52
#, python-brace-format
msgid ". IP: {ip}"
msgstr ". IP: {ip}"

#: auth/handlers.py:72
msgid "Demo version"
msgstr "Демонстрационная версия"

#: auth/license/handlers.py:35 common/veil_decorators.py:130
#: tests/test_auth_v2.py:75
msgid "Invalid permissions"
msgstr "Недостаточно прав"

#: auth/license/handlers.py:50
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: auth/license/handlers.py:58
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: auth/license/handlers.py:60
msgid "Try to upload invalid license key"
msgstr "Неудачная попытка загрузить лицензионный ключ"

#: auth/license/handlers.py:63
msgid "Valid license key is uploaded"
msgstr "Лицензионный ключ загружен"

#: auth/models.py:142
msgid "Role {} is added to user {}"
msgstr "Роль {} назначена пользователю {}"

#: auth/models.py:148
msgid "Role {} is assigned to user {}"
msgstr "Роль {} назначена пользователю {}"

#: auth/models.py:160
msgid "Roles: {} was deleted to user {}"
msgstr "Роли: {} удалены у пользователя {}"

#: auth/models.py:172
msgid "Group {} is removed for user {}"
msgstr "Группа {} удалена у пользователя {}"

#: auth/models.py:178
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: auth/models.py:190
msgid "There is no more active superuser."
msgstr "Больше нет активного суперпользователя."

#: auth/models.py:195
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: auth/models.py:223
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: auth/models.py:241
msgid "User {} created with role {}."
msgstr "Пользователь {} создан с ролью {}."

#: auth/models.py:264 auth/models.py:268
msgid "Roles: {}"
msgstr "Роли: {}"

#: auth/models.py:265
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал суперпользователем."

#: auth/models.py:269
#, python-brace-format
msgid "User {username} has left a superuser."
msgstr "Пользователь {username} перестал быть суперпользователем."

#: auth/models.py:273
msgid "Values of user {} is changed"
msgstr "Параметры пользователя {} изменены"

#: auth/models.py:289
#, python-brace-format
msgid "{auth_type}: user {username} has been logged in successfully. IP: {ip}."
msgstr "{auth_type}: пользователь {username} успешно зарегистрирован. IP: {ip}."

#: auth/models.py:310
#, python-brace-format
msgid "User {username} has logged out."
msgstr "Пользователь {username} вышел из системы."

#: auth/models.py:403
msgid "Group {} is created."
msgstr "Группа {} создана."

#: auth/models.py:418
msgid "Values of group {} is updated"
msgstr "Параметры группы {} обновлены"

#: auth/models.py:442
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: auth/models.py:446
msgid "User {} is already in group {}"
msgstr "Пользователь {} уже находится в группе {}"

#: auth/models.py:456
msgid "Removing user {} from group {}"
msgstr "Удаление пользователя {} из группы {}"

#: auth/models.py:463
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: auth/models.py:467
msgid "Group {} has already role {}"
msgstr "Группе {} уже назначена роль {}."

#: auth/models.py:477
msgid "Roles: {} was deleted to group {}"
msgstr "Роли: {} удалены из группы {}"

#: auth/user_schema.py:24 auth/user_schema.py:158
msgid "No such user."
msgstr "Нет такого пользователя."

#: auth/user_schema.py:34
msgid "username must contain >= 3 chars (letters, digits, _, -, +) and can't contain any spaces"
msgstr "username должно быть >= 3 символов (буквы, цифры, _, -, +) и не содержать пробелов"

#: auth/user_schema.py:41
msgid "Email {} is already busy"
msgstr "Email {} уже используется"

#: auth/user_schema.py:49
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: auth/user_schema.py:64
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: auth/user_schema.py:70
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: auth/user_schema.py:154
msgid "Scpecify id or username."
msgstr "Укажите ID или имя пользователя."

#: auth/utils/veil_jwt.py:26
msgid "Token invalid."
msgstr "Недействительный токен."

#: auth/utils/veil_jwt.py:31
msgid "Token expired."
msgstr "Срок действия токена истек."

#: auth/utils/veil_jwt.py:84
msgid "Error with JWT decode"
msgstr "Ошибка JWT декодирования."

#: auth/utils/veil_jwt.py:94 auth/utils/veil_jwt.py:96
#: auth/utils/veil_jwt.py:98
msgid "invalid header authorization"
msgstr "недействительный заголовок авторизации"

#: auth/utils/veil_jwt.py:102
msgid "Missing Authorization header"
msgstr "Пропущен заголовок авторизации"

#: common/veil_client.py:50
msgid "jwt {}"
msgstr "jwt {}"

#: common/veil_client.py:130
msgid "Controller {} connection error."
msgstr "Ошибка подключения к контроллеру {}."

#: common/veil_client.py:134
msgid "Fail to fetch resource from ECP."
msgstr "Ошибка доступа к ресурсу из ECP"

#: common/veil_client.py:154
msgid "Can't process Content-Type."
msgstr "Не может обработаться Content-Type."

#: common/veil_decorators.py:27
msgid "'body' index in args must be 4, but in the same time 'body' in kwargs"
msgstr "Индекс 'body' это 4 параметра в аргументах. Но в то же время 'body' в kwargs."

#: common/veil_decorators.py:68
msgid "Can check only kwargs or args. Not both at the same time."
msgstr "Можете проверить только kwargs или аргументы. Не оба обдовременно."

#: common/veil_decorators.py:73 common/veil_decorators.py:87
msgid "The parameters to be checked are in an dict. Can't explicitly match values with tuple."
msgstr "Параметры, которые нужно проверить, указаны в формате словаря. Значения не могут явно сопоставиться с кортежем."

#: common/veil_decorators.py:83
msgid "Value {} is invalid. Valid values are: {}"
msgstr "Значение {} неверно. Допустимые значения: {}"

#: common/veil_decorators.py:90
msgid "Parameter {} is necessary."
msgstr "Параметр {} необходим."

#: common/veil_decorators.py:95
msgid "Parameter {} value {} is invalid. Valid values are: {}"
msgstr "Параметр {} значения {} неверный. Допустимые значения: {}"

#: common/veil_decorators.py:128
msgid "IP: {}. username: {}"
msgstr "IP: {}. Пользователь: {}."

#: common/veil_errors.py:171
msgid "Controller is not available."
msgstr "Контроллер недоступен."

#: common/veil_errors.py:189
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: common/veil_errors.py:195
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: common/veil_errors.py:201
msgid "Critical controller error."
msgstr "Критическая ошибка контроллера."

#: common/veil_validators.py:32
msgid "Field \"{}\" - {}"
msgstr "Поле \"{}\" - {}"

#: controller/client.py:32
msgid "Auth failed."
msgstr "Ошибка авторизации."

#: controller/models.py:137
msgid "No such controller"
msgstr "Нет такого контроллера."

#: controller/models.py:146
msgid "Controller {} check failed."
msgstr "Проверка контроллера {} не удалась."

#: controller/models.py:160
msgid "Can't login login to controller {}"
msgstr "Не получается войти на контроллер {}"

#: controller/models.py:174
msgid "Veil ECP version should be 4.2 or 4.3. Current version is incompatible."
msgstr "Версия VeiL ECP должна быть 4.2 или 4.3. Текущая версия не поддерживается."

#: controller/models.py:191
msgid "Successfully added new controller {} with address {}."
msgstr "Успешно добавлен новый контроллер {} с адресом {}."

#: controller/models.py:244
msgid "Address is unreachable"
msgstr "Адрес недоступен"

#: controller/models.py:274
msgid "Error with controller update: {}"
msgstr "Ошибка с обновлением контроллера: {}"

#: controller/models.py:286
msgid "Successfully update controller {} with address {}."
msgstr "Успешно обновлен контроллер {} с адресом {}."

#: controller/models.py:309
msgid "Controller has pool of virtual machines. Please completely remove."
msgstr "У контроллера есть пулы виртуальных машин. Выполните полное удаление."

#: controller/models.py:333
#, python-brace-format
msgid "Controller {name} had completely remove."
msgstr "Выполнено полное удаление контроллера {name}."

#: controller/models.py:347
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: controller/models.py:365
msgid "Controller {} has been deactivated."
msgstr "Контроллер {} деактивирован."

#: controller/schema.py:66
msgid "Controller name cannot be empty."
msgstr "Имя контроллера не может быть пустым."

#: controller/schema.py:73 controller/schema.py:78
msgid "Add new controller {}: operation failed."
msgstr "Ошибка добавления нового контроллера {}."

#: controller/schema.py:101 controller/schema.py:130 controller/schema.py:153
#: controller/schema.py:182
msgid "No such controller."
msgstr "Нет такого контроллера."

#: controller/schema.py:111
msgid "Fail to update controller {}"
msgstr "Ошибка обновления контроллера {}"

#: controller/schema.py:138
msgid "Controller"
msgstr "Контроллер"

#: controller_resources/schema.py:321 controller_resources/schema.py:374
#: controller_resources/schema.py:426
msgid "The sort parameter is incorrect"
msgstr "Неверный параметр сортировки"

#: database.py:80
msgid "Incorrect sort parameter {}"
msgstr "Неверный параметр сортировки {}"

#: database.py:90
msgid "Incorrect request parameter {}"
msgstr "Неверный параметр запроса {}"

#: journal/event/schema.py:156
msgid "No such event."
msgstr "Нет такого события."

#: journal/event/schema.py:207
msgid "Journal is clear."
msgstr "Журнал очищен."

#: pool/models.py:157
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: pool/models.py:373
msgid "User {} has been included to pool {}"
msgstr "Пользователь {} был включен в пул {}"

#: pool/models.py:375 pool/models.py:402
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: pool/models.py:386
msgid "Removing user {} from pool {}"
msgstr "Удаление пользователя {} из пула {}"

#: pool/models.py:400
msgid "Group {} has been included to pool {}"
msgstr "Группа {} была включена в пул {}"

#: pool/models.py:413
msgid "Removing group {} from pool {}"
msgstr "Удаление группы {} из пула {}"

#: pool/models.py:426
msgid "Role {} has been set to pool {}."
msgstr "Роль {} добавлена в пул {}."

#: pool/models.py:428
msgid "Pool already has role."
msgstr "Пул уже имеет роль."

#: pool/models.py:438
msgid "Roles: {} was deleted to pool {}"
msgstr "Роли: {} удалены в пуле {}"

#: pool/models.py:463
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: pool/models.py:477
msgid "Pool has VMs. Please completely remove."
msgstr "У пула виртуальных машин есть виртуальные машины. Выполните полное удаление."

#: pool/models.py:500
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: pool/models.py:508
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: pool/models.py:515
msgid "Pool {} has been deactivated."
msgstr "Пул {} деактивирован."

#: pool/models.py:588
msgid "HttpError: {}"
msgstr "Ошибка Http: {}"

#: pool/models.py:597
msgid "VM with id {} not found in any controllers"
msgstr "Виртуальная машина с {} ID не найдена ни на одном из известных контроллеров"

#: pool/models.py:616
msgid "StaticPool: Create Pool"
msgstr "Статический пул: создание пула"

#: pool/models.py:624
msgid "StaticPool: Create StaticPool"
msgstr "Статический пул: создание статического пула"

#: pool/models.py:627
msgid "StaticPool: Create VMs"
msgstr "Статический пул: создание виртуальных машин"

#: pool/models.py:629
msgid "VM info {}"
msgstr "Информация о ВМ {}"

#: pool/models.py:635
msgid "VM {} created."
msgstr "ВМ {} создана."

#: pool/models.py:637
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: pool/models.py:651
msgid "Static pool {} is updated."
msgstr "Статический пул {} обновлен."

#: pool/models.py:746
msgid "Create Pool {}"
msgstr "Создание пула {}"

#: pool/models.py:754
msgid "Create AutomatedPool {}"
msgstr "Создание автоматического пула {}"

#: pool/models.py:789
msgid "Update Pool values for AutomatedPool {}"
msgstr "Обновление значений пула для автоматического пула {}"

#: pool/models.py:804
msgid "Update AutomatedPool values for {}"
msgstr "Обновление значений автоматического пула для {}"

#: pool/models.py:808
#, python-brace-format
msgid "Automated pool {name} updated."
msgstr "Автоматический пул {name} обновлен."

#: pool/models.py:834
msgid "add_domain {}, attempt № {}, of {}"
msgstr "Добавление домена {}, попытка № {} из {}"

#: pool/models.py:838
msgid "VM creation task id: {}"
msgstr "ID задачи создания виртуальной машины: {}"

#: pool/models.py:849
msgid "Subscribe to ws messages."
msgstr "Подпишитесь на сообщения ws."

#: pool/models.py:854
msgid "Wait for result."
msgstr "Ожидайте результата."

#: pool/models.py:860
msgid "Create virtual machine"
msgstr "Создание виртуальной машины."

#: pool/models.py:893
msgid "Could not get the response about result of creation VM on ECP by WS. Task status check."
msgstr "Не удалось получить ответ о результате создания ВМ на ECP по WS. Проверим статус задачи."

#: pool/models.py:897
msgid "Probably task is not done. Check VM status."
msgstr "Вероятно, задание не выполнено. Проверьте состояние ВМ."

#: pool/models.py:920
msgid "VM {} is added to Automated pool {}"
msgstr "Виртуальная машина добавлена в автоматический пул {}"

#: pool/models.py:926
msgid "Error with create VM {}"
msgstr "Ошибка с созданием виртуальной машины {}"

#: pool/models.py:938
msgid "Add {} initial vms for pool {}. Controller address: {}"
msgstr "Добавление {} начальных виртуальных машин для пула {}. Адрес контроллера: {}."

#: pool/models.py:945
msgid "Pool {} os type is: {}"
msgstr "Операционная система пула {}: {}"

#: pool/models.py:948
msgid "Automated pool creation started"
msgstr "Автоматическое создание пула началось"

#: pool/models.py:959
msgid "Created {} VMs from {} at the Automated pool {}"
msgstr "Создание {} виртуальных машин из {} автоматического пула {}"

#: pool/models.py:977
msgid "Can't create VM"
msgstr "Невозможно создать виртуальную машину"

#: pool/models.py:984
msgid "Initial VM amount {} at the Automated pool {}"
msgstr "Начальное количество виртуальных машин {} в автоматическом пуле {}"

#: pool/models.py:987
msgid "Automated pool created with errors. VMs created: {}. Required: {}"
msgstr "Автоматический пул создан с ошибками. Созданные виртуальные машины: {}. Необходимо: {}."

#: pool/models.py:1004
msgid "Could not create the required number of machines."
msgstr "Не удалось создать необходимое количество машин."

#: pool/models.py:1053
msgid "VM creating error:"
msgstr "Ошибка создания виртуальной машины:"

#: pool/models.py:1059
msgid "Delete VMs for AutomatedPool {}"
msgstr "Удаление виртуальных машин для автоматического пула {}"

#: pool/models.py:1062 vm/models.py:234
msgid "VM"
msgstr "Виртуальная машина"

#: pool/pool_task_manager.py:70
msgid "Logic error: no such pool"
msgstr "Логическая ошибка: нет такого пула"

#: pool/schema.py:55 pool/schema.py:362 pool/schema.py:389
msgid "No such pool."
msgstr "Нет такого пула."

#: pool/schema.py:67
msgid "ip-address probably invalid."
msgstr "Возможно, неверный IP адрес."

#: pool/schema.py:77
msgid "Pool name must contain only characters, digits, _, -"
msgstr "Имя пула должно содержать только буквы, цифры, _, -"

#: pool/schema.py:88
msgid "Template name of VM must contain only characters, digits, _, -"
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, _, -"

#: pool/schema.py:96
msgid "Initial number of VM must be in {}-{} interval"
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:112
msgid "Number of created VM must be in {}-{} interval"
msgstr "Число создаваемых виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:133 pool/schema.py:688
msgid "Maximal number of created VM should be less than initial number of VM"
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ"

#: pool/schema.py:135 pool/schema.py:690
msgid "Maximal number of created VM must be in [{} {}] interval"
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: pool/schema.py:380
msgid "Pool"
msgstr "Пул"

#: pool/schema.py:451
msgid "StaticPool: Get additional info from Veil"
msgstr "Статический пул: получение дополнительной информации о Veil"

#: pool/schema.py:459
msgid "All of VM must be at one server"
msgstr "Все виртуальные машины должны быть на одном сервере"

#: pool/schema.py:461
msgid "StaticPool: Determine cluster"
msgstr "Статический пул: Определение кластера"

#: pool/schema.py:469
msgid "VM has no disks."
msgstr "ВМ не имеет дисков."

#: pool/schema.py:482
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: pool/schema.py:489
msgid "Fail with remote access enable."
msgstr "Не удалось включить удаленный доступ к виртуальным машинам."

#: pool/schema.py:507 pool/schema.py:559
msgid "List of VM should not be empty"
msgstr "Список виртуальных машин не должен быть пустым."

#: pool/schema.py:523
msgid "VM {} is at server different from pool server now"
msgstr "ВМ {} находится на сервере отличном от сервера пула."

#: pool/schema.py:526
msgid "VM {} is already in one of pools"
msgstr "Виртуальная машина {} уже в одном из пулов."

#: pool/schema.py:531
msgid "All VMs on node: {}"
msgstr "Все виртуальные машины на узле: {}"

#: pool/schema.py:542
msgid "Vm {} is added to pool {}"
msgstr "Виртуальная машина {} добавлена в пул {}"

#: pool/schema.py:568
msgid "VM doesn't belong to specified pool"
msgstr "Виртуальная машина не принадлежит заданному пулу"

#: pool/schema.py:596
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: pool/schema.py:637
msgid "Failed to create automated pool {}. Name must be unique."
msgstr "Ошибка создания автоматического пула {}. Имя должно быть уникальным."

#: pool/schema.py:693
msgid "Maximal number of created VM can not be reduced."
msgstr "Максимальное количество создаваемых виртуальных машин не может быть уменьшено."

#: pool/schema.py:711
msgid "Failed to update automated pool {}. Name must be unique."
msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#: resources_monitoring/handlers.py:79
msgid "destructor VdiFrontWsHandler"
msgstr "Деструктор VdiFrontWsHandler"

#: resources_monitoring/handlers.py:92
msgid "Message: {}"
msgstr "Сообщение: {}"

#: resources_monitoring/handlers.py:106
msgid "Unknown subscription source"
msgstr "Неизвестный источник подписки"

#: resources_monitoring/handlers.py:117
msgid "already subscribed"
msgstr "уже подписан"

#: resources_monitoring/handlers.py:121
msgid "not subscribed"
msgstr "не подписан"

#: resources_monitoring/handlers.py:132
msgid "WebSocket closed"
msgstr "WebSocket закрыт"

#: resources_monitoring/handlers.py:164
msgid "Write error"
msgstr "Ошибка записи"

#: resources_monitoring/resources_monitor.py:138
#, python-brace-format
msgid "{cls}: an not connect to {ip}"
msgstr "{cls}: не подключен к {ip}."

#: resources_monitoring/resources_monitor.py:168
msgid "{} Closing ws connection {}"
msgstr "{} Закрытие ws соединения {}"

#: resources_monitoring/resources_monitor_manager.py:27
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}"
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: resources_monitoring/resources_monitor_manager.py:36
msgid "{}: Started"
msgstr "{}: Запущен"

#: resources_monitoring/resources_monitor_manager.py:71
msgid "Controller {ip} is already monitored!"
msgstr "Контроллер {ip} уже отслеживается монитором ресурсов."

#: resources_monitoring/resources_monitor_manager.py:77
#, python-brace-format
msgid "Resource monitor for controller {ip} connected"
msgstr "Мониторинг ресурсов для контроллера {ip} подключен"

#: resources_monitoring/resources_monitor_manager.py:97
#, python-brace-format
msgid "Resource monitor for controller {ip} stopped."
msgstr "Остановлен мониторинг ресурсов контроллера {ip}."

#: tests/test_auth_v2.py:125
msgid "Invalid credentials (ldap)"
msgstr "Неверные учетные данные (ldap)"

#: thin_client_api/handlers.py:63
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: thin_client_api/handlers.py:72
msgid "Pool not found."
msgstr "Пул не найден."

#: thin_client_api/handlers.py:83
msgid "User does not have permission to use pool."
msgstr "Пользователь не имеет разрешения на использование пула."

#: thin_client_api/handlers.py:114
msgid "Pool has not free machines"
msgstr "В пуле нет свободных машин"

#: thin_client_api/handlers.py:127 thin_client_api/handlers.py:136
msgid "VM is unreachable on ECP Veil."
msgstr "VM недоступна на ECP Veil."

#: thin_client_api/handlers.py:151
msgid "VM does not support RDP"
msgstr "Виртуальная машина не поддерживает RDP"

#: thin_client_api/handlers.py:173
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: thin_client_api/handlers.py:176
msgid "There is no pool with id: {}"
msgstr "Отсутствует пул с ID: {}."

#: thin_client_api/handlers.py:180
msgid "User {} has no VM on pool {}"
msgstr "У пользователя {} нет виртуальной машины в пуле {}"

#: vm/models.py:77
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: vm/models.py:88
msgid "VM {} is created"
msgstr "Виртуальная машина {} создана"

#: vm/models.py:101
msgid "Fail to remove VM {} from ECP: "
msgstr "Ошибка удаления ВМ {} из ECP: "

#: vm/models.py:102
msgid "Vm {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: vm/models.py:125
msgid "User {} is added to VM {}"
msgstr "Пользователь {} назначен виртуальной машине {}"

#: vm/models.py:127
msgid "Vm already has permission."
msgstr "Вм уже имеет разрешение"

#: vm/models.py:138
msgid "VM {} is clear from users"
msgstr "ВМ {} освобождена от пользователей"

#: vm/models.py:202
msgid "Not enough free space on data pool"
msgstr "Недостаточно свободного места в пуле данных"

#: vm/models.py:205
msgid "Controller can't create VM. Unknown node."
msgstr "Контроллер не может создать ВМ. Неизвестный узел."

#: vm/models.py:208
msgid "Controller can't create VM. Copy not zfs disks with snapshot to zfs pool"
msgstr "Контроллер не может создать ВМ. Копирование не ZFS дисков со снэпшотами на ZFS пул."

#: vm/models.py:218
msgid "Controller can't process request. See VeiL ECP logs."
msgstr "Контроллер не смог обработать запрос. Смотрите логи VeiL ECP."

#: vm/models.py:235
msgid "Vm {} removed from pool"
msgstr "ВМ {} удалена из пула"

#: vm/schema.py:156
msgid "There is no VM {}"
msgstr "Нет ВМ {}."

#: vm/schema.py:172
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: vm/schema.py:216
msgid "GraphQL: Resolving template info"
msgstr "GraphQL: разрешение информации о шаблоне."

#: vm/schema.py:221
msgid "Template data could not be retrieved: {}"
msgstr "Не удалось получить данные Шаблона: {}"

#: vm/schema.py:231
msgid "VM data could not be retrieved: {}"
msgstr "Не удалось получить данные виртуальной машины: {}"

#: vm/schema.py:242
msgid "Templates list could not be retrieved: {}"
msgstr "Не удалось получить список шаблонов: {}"

#: vm/schema.py:278 vm/schema.py:356
msgid "Incorrect sort parameter"
msgstr "Неверный параметр сортировки"

#: vm/schema.py:286
msgid "GraphQL: Resolving VMs"
msgstr "GraphQL: разрешение виртуальных машин"

#: vm/schema.py:293
msgid "VMs list could not be retrieved: {}"
msgstr "Не удалось получить список виртуальных машин: {}"

#: vm/schema.py:298
msgid "GraphQL: VM type list:"
msgstr "GraphQL: список типов виртуальных машин:"
